### ISSUE TITLE
Bug: Error when trying to delete a relation entity field (in PR #1080)

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#1104]
**Describe the bug**
An error is received when trying to delete a related entity field that was created without the opposite related entity field.

```
{"errors":[{"message":"\nInvalid `prisma.entityField.delete()` invocation:\n\n{\n  where: {\n    entityVersionId_permanentId: {\n+     permanentId: String,\n      entityVersionId: 'ckhln2o0n004788jnky97pnrs'\n    }\n  }\n}\n\nArgument permanentId for where.entityVersionId_permanentId.permanentId is missing.\n\nNote: Lines with + are required\n","locations":[{"line":2,"column":3}],"path":["deleteEntityField"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["Error: ","Invalid `prisma.entityField.delete()` invocation:","","{","  where: {","    entityVersionId_permanentId: {","+     permanentId: String,","      entityVersionId: 'ckhln2o0n004788jnky97pnrs'","    }","  }","}","","Argument permanentId for where.entityVersionId_permanentId.permanentId is missing.","","Note: Lines with + are required","","    at GqlResolverExceptionsFilter.catch (C:\\projects\\amplication.git\\amplication\\packages\\amplication-server\\dist\\src\\filters\\GqlResolverExceptions.filter.js:74:23)","    at ExternalExceptionsHandler.invokeCustomFilters (C:\\projects\\amplication.git\\amplication\\packages\\amplication-server\\node_modules\\@nestjs\\core\\exceptions\\external-exceptions-handler.js:34:32)","    at ExternalExceptionsHandler.next (C:\\projects\\amplication.git\\amplication\\packages\\amplication-server\\node_modules\\@nestjs\\core\\exceptions\\external-exceptions-handler.js:13:29)","    at C:\\projects\\amplication.git\\amplication\\packages\\amplication-server\\node_modules\\@nestjs\\core\\helpers\\external-proxy.js:14:42","    at runMicrotasks (<anonymous>)","    at processTicksAndRejections (internal/process/task_queues.js:97:5)"]}}}],"data":null}

```

**To Reproduce**
1. Go to an existing application that was created before v0.2.0
2. Try to delete a field of Type "Relation to another Entity"
3. See error

**Comment by yuval-hazaz** [comment]
resolved in #1080
