### ISSUE TITLE
🐛 Bug Report: Generated App Tests are failing

### ISSUE THREAD

**Issue by shubhwip** [amplication/amplication#3745]
### What happened?

I generated application using Amplication Data Service Generator Locally and Tests are failing for the generated app.
```
[Nest] 13076  - 09/03/2022, 2:16:50 PM   ERROR [ExceptionsHandler] Invalid role(s): []
AccessControlError: Invalid role(s): []
    at new AccessControlError (/Users/shubhamjain/SJ/Projects/amplication/packages/amplication-data-service-generator/generated/server/node_modules/accesscontrol/lib/core/AccessControlError.js:24:28)
    at Object.getFlatRoles (/Users/shubhamjain/SJ/Projects/amplication/packages/amplication-data-service-generator/generated/server/node_modules/accesscontrol/lib/utils.js:550:19)
    at Object.getUnionAttrsOfRoles (/Users/shubhamjain/SJ/Projects/amplication/packages/amplication-data-service-generator/generated/server/node_modules/accesscontrol/lib/utils.js:739:27)
    at new Permission (/Users/shubhamjain/SJ/Projects/amplication/packages/amplication-data-service-generator/generated/server/node_modules/accesscontrol/lib/core/Permission.js:51:43)
    at RolesBuilder.Object.<anonymous>.AccessControl.permission (/Users/shubhamjain/SJ/Projects/amplication/packages/amplication-data-service-generator/generated/server/node_modules/accesscontrol/lib/AccessControl.js:481:16)
    at AclFilterResponseInterceptor.intercept (/Users/shubhamjain/SJ/Projects/amplication/packages/amplication-data-service-generator/generated/server/src/interceptors/aclFilterResponse.interceptor.ts:25:42)
    at /Users/shubhamjain/SJ/Projects/amplication/packages/amplication-data-service-generator/generated/server/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:23:36
    at InterceptorsConsumer.intercept (/Users/shubhamjain/SJ/Projects/amplication/packages/amplication-data-service-generator/generated/server/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:25:24)
    at /Users/shubhamjain/SJ/Projects/amplication/packages/amplication-data-service-generator/generated/server/node_modules/@nestjs/core/router/router-execution-context.js:46:60
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### What you expected to happen

Tests should pass for generated application.

### How to reproduce

Prepare Amplication Setup Locally
 - Clone Repo
 - `npm install`
 - `npm run setup:dev`

Go into amplication data service generator
 - `npm run generate-test-data-service`

Go into generated/server folder
 - `npm run test`

### Amplication version

0.16.0

### Environment

Node Version : v14.20.0
NPM : 8.15.1
Docker : Docker version 20.10.17, build 100c701
Browser : Chrome
Environment : Local
OS : MacOS M1

**Comment by yuval-hazaz** [comment]
Thanks @shubhwip 
We will look into it soon

**Comment by woodenfish** [comment]
I found the solution.  User roles data structure been changed to `{"roles": ["user"]}`. You can fix it following screenshot

![image](https://user-images.githubusercontent.com/3112528/191458234-37f297da-ae16-42db-b67e-65f84a7328e9.png)

**Comment by shubhwip** [comment]
@woodenfish It has changed recently i guess, tests has been failing before that. 
Now I tried your suggestion as well and synched from latest master and it seems tests are still not happy but thanks for pointing this out.

**Comment by shanurrahman** [comment]
Facing exactly the same issue

**Comment by shubhwip** [comment]
@tupe12334 When ACGuard is commented out in specs then tests pass
```
      .overrideGuard(DefaultAuthGuard)
      .useValue(basicAuthGuard)
      //.overrideGuard(ACGuard)
      //.useValue(acGuard)
      .compile();
```
What could be the reason ?

**Comment by tupe12334** [comment]
Hi @shubhwip I saw your solution, and instead of removing the guard logic, I overrode the interceptors logic as well.
Please see my #3967 PR if you want; you can even leave some comments if you have any.
