### ISSUE TITLE
🐛 Bug Report: Backend + Kafka server fails to launch

### ISSUE THREAD

**Issue by katrieltsepelevish** [amplication/amplication#4602]
### What happened?

After launching the Client and the Backend applications in development mode and reaching the website looks like the login and register responses fail with a 'Failed to fetch' error and the endpoint itself fails with 'ERR_CONNECTION REFUSED' while the GraphQL's client is down in backend side (PORT: 3000).

The server's launch up failed to lunch the Kafka server with 'KafkaJSNonRetriableError' and closed the connection after the number of retries was exceeded.

```bash
[Nest] 12459  - 12/09/2022, 9:56:29 AM   ERROR [ServerKafka] ERROR [BrokerPool] Closed connection {"timestamp":"2022-12-09T07:56:29.018Z","logger":"kafkajs","retryCount":2,"retryTime":1086}
[Nest] 12459  - 12/09/2022, 9:56:30 AM   ERROR [ServerKafka] ERROR [BrokerPool] Closed connection {"timestamp":"2022-12-09T07:56:30.126Z","logger":"kafkajs","retryCount":3,"retryTime":2470}
[Nest] 12459  - 12/09/2022, 9:56:32 AM   ERROR [ServerKafka] ERROR [BrokerPool] Closed connection {"timestamp":"2022-12-09T07:56:32.606Z","logger":"kafkajs","retryCount":4,"retryTime":5754}
[Nest] 12459  - 12/09/2022, 9:56:38 AM   ERROR [ServerKafka] ERROR [BrokerPool] Closed connection {"timestamp":"2022-12-09T07:56:38.374Z","logger":"kafkajs","retryCount":5,"retryTime":10026}
KafkaJSNonRetriableError
  Caused by: KafkaJSConnectionClosedError: Closed connection
    at Socket.onEnd (/Users/Personal/workspaces/amplication/node_modules/kafkajs/src/network/connection.js:136:13)
    at Socket.emit (node:events:538:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  name: 'KafkaJSNumberOfRetriesExceeded',
  retriable: false,
  helpUrl: undefined,
  originalError: KafkaJSConnectionClosedError: Closed connection
      at Socket.onEnd (/Users/Personal/workspaces/amplication/node_modules/kafkajs/src/network/connection.js:136:13)
      at Socket.emit (node:events:538:35)
      at endReadableNT (node:internal/streams/readable:1345:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21) {
    retriable: true,
    helpUrl: undefined,
    broker: 'localhost:9092',
    code: undefined,
    host: 'localhost',
    port: 9092
  },
  retryCount: 5,
  retryTime: 10026
}
```

### What you expected to happen

To successfully launch up the server in development mode and succeed in signing up as a new user/login as an already existing user.

### How to reproduce

Go through the steps of [Getting started with local development](https://github.com/amplication/amplication#getting-started-with-local-development) and launch at the Amplication client and server in development mode.

### Amplication version

1.1.1

### Environment

branch: next

**Comment by souravjain540** [comment]
@abrl91 can you help?

**Comment by abrl91** [comment]
@katrieltsepelevish please read this: https://github.com/amplication/amplication/releases/tag/v0.13.1
