### ISSUE TITLE
Server's Prisma crash on requests

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#4637]
When you setup a clean workspace the server bootup but crashes when you send a request with this error:
```bash
error: Could not find mapping for model User {"clientVersion":"4.6.1","requestData":{"hostname":"localhost","ip":"::1","query":"query getCurrentWorkspace {
  currentWorkspace {
    id
    name
    subscription {
      id
      workspaceId
      subscriptionPlan
      status
      nextBillDate
      cancelUrl
      updateUrl
      price
      cancellationEffectiveDate
      __typename
    }
    gitOrganizations {
      id
      name
      installationId
      type
      __typename
    }
    __typename
  }
}
"},"service":"amplication-server","stack":"Error: Could not find mapping for model User
    at PrismaService.<anonymous> (/Users/amitbarletz/Dev/forks/amplication/dist/packages/amplication-server/webpack:/amplication/packages/amplication-prisma-db/prisma/generated-prisma-client/runtime/index.js:35312:17)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/amitbarletz/Dev/forks/amplication/node_modules/tslib/tslib.js:115:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)","timestamp":"2022-12-13T13:02:11.686Z"}
```

**Comment by abrl91** [comment]
and we also have this error in the docker container for the DB
![image](https://user-images.githubusercontent.com/39680385/208116464-3dcf2c5a-e922-4446-ab59-cf84cd489f7d.png)
