### ISSUE TITLE
🐛 Bug Report: Can't connect to repo in Sandbox env

### ISSUE THREAD

**Issue by EugeneTseitlin** [amplication/amplication#5004]
### What happened?

Connecting project to GitHub can't be completed.
Here is the error from popup window that opened for connecting repo to project:
Error: secretOrPrivateKey must be an asymmetric key when using RS256
    at new t (vendor.5bbb11d45f783417.js:102:1744813)
    at vendor.5bbb11d45f783417.js:102:1724856
    at n (vendor.5bbb11d45f783417.js:102:1699991)
    at vendor.5bbb11d45f783417.js:102:1699916
    at new Promise (<anonymous>)
    at Object.then (vendor.5bbb11d45f783417.js:102:1699882)
    at Object.next (vendor.5bbb11d45f783417.js:102:1700001)
    at x (vendor.5bbb11d45f783417.js:102:1826204)
    at w (vendor.5bbb11d45f783417.js:102:1826710)
    at t.next (vendor.5bbb11d45f783417.js:102:1827243)

### What you expected to happen

Connection to GitHub repo should be completed successfully.

### How to reproduce

In Sandbox Env:
1. Create a project
2. Go to Project Configuration of project that you've created. 
3. Go to Connect to GitHub page. 
4. Click Connect to GitHub button, select repo, confirm.
After these steps you should see that popup window stuck.

**Comment by tupe12334** [comment]
I think its because we probably missing env in the next env

**Comment by levivannoort** [comment]
Tried to reproduce but I didnt ran into the issue (even uninstalled the github app, et cetera)

**Comment by tupe12334** [comment]
@levivannoort This issue is not relevant anymore
