### ISSUE TITLE
Data Service Generator: Undefined doesn't match field name

### ISSUE THREAD

**Issue by iddan** [amplication/amplication#501]
**Describe the bug**
Stack trace:

```
Error: undefined does not match field \"name\": string of type Identifier
    at addParam (/packages/amplication-data-service-generator/node_modules/ast-types/lib/types.js:447:27)
    at /packages/amplication-data-service-generator/node_modules/ast-types/lib/types.js:470:25
    at Array.forEach (<anonymous>)
    at Object.builder [as identifier] (/packages/amplication-data-service-generator/node_modules/ast-types/lib/types.js:468:35)
    at createFieldClassProperty (/packages/amplication-data-service-generator/dist/resource/dto/create-dto.js:200:83)
    at /packages/amplication-data-service-generator/dist/resource/dto/create-dto.js:109:25
    at Array.map (<anonymous>)
    at createCreateInput (/packages/amplication-data-service-generator/dist/resource/dto/create-dto.js:109:10)
    at Object.createDTOModules (/packages/amplication-data-service-generator/dist/resource/dto/create-dto.js:57:9)
    at createResourceModules (/packages/amplication-data-service-generator/dist/resource/create-resource.js:53:37)
```

Internal logs:
https://console.cloud.google.com/logs/query;query=resource.type%20%3D%20%22cloud_run_revision%22%0Aresource.labels.service_name%20%3D%20%22cloudrun-srv%22%0AjsonPayload.level%20%3D%20%22error%22%0AjsonPayload.message%3D%22undefined%20does%20not%20match%20field%20%5C%22name%5C%22:%20string%20of%20type%20Identifier%22;timeRange=2020-09-19T07:57:05.404Z%2F2020-09-27T07:57:05.404Z?project=amplication-production

**Comment by yuval-hazaz** [comment]
@iddan  This happened with the sample app since the links between the entities was incorrect. 
We should not see this error again as the relationship is validated when creating new fields. 
for future cases, I still think we should validate this on code generation phase and provide a more detailed error.
