### ISSUE TITLE
Server: Error occurred during query execution

### ISSUE THREAD

**Issue by iddan** [amplication/amplication#506]
**Describe the bug**

Stack Trace:

```
Error: Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Closed, cause: None }) })
    at PrismaClientFetcher.request (/packages/amplication-server/node_modules/@prisma/client/runtime/index.js:1:228459)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

GraphQL Query:

```graphql
query builds($appId: String!) {
  builds(where: { app: { id: $appId } }, orderBy: { createdAt: Desc }) {
    id
    appId
    version
    message
    createdAt
    actionId
    createdBy {
      id
      account {
        firstName
        lastName
        __typename
      }
      __typename
    }
    status
    archiveURI
    __typename
  }
}
```

---

Stack Trace:

```
Error: Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Closed, cause: None }) })
    at PrismaClientFetcher.request (/packages/amplication-server/node_modules/@prisma/client/runtime/index.js:1:228459)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

GraphQL Query:

```graphql
query actionLog($actionId: String!) {
  action(where: { id: $actionId }) {
    id
    createdAt
    steps {
      id
      createdAt
      message
      status
      completedAt
      logs {
        id
        createdAt
        message
        meta
        level
        __typename
      }
      __typename
    }
    __typename
  }
}
```

---

Stack Trace:

```
Error: Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Closed, cause: None }) })
    at PrismaClientFetcher.request (/packages/amplication-server/node_modules/@prisma/client/runtime/index.js:1:228459)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
```

GraphQL Query:

```graphql
query builds($appId: String!) {
  builds(where: { app: { id: $appId } }, orderBy: { createdAt: Desc }) {
    id
    appId
    version
    message
    createdAt
    actionId
    createdBy {
      id
      account {
        firstName
        lastName
        __typename
      }
      __typename
    }
    status
    archiveURI
    __typename
  }
}
```

---

Stack Trace:

```
Error: Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Closed, cause: None }) })
    at PrismaClientFetcher.request (/packages/amplication-server/node_modules/@prisma/client/runtime/index.js:1:228459)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

GraphQL Query:

```graphql
query actionLog($actionId: String!) {
  action(where: { id: $actionId }) {
    id
    createdAt
    steps {
      id
      createdAt
      message
      status
      completedAt
      logs {
        id
        createdAt
        message
        meta
        level
        __typename
      }
      __typename
    }
    __typename
  }
}
```

---

Stack Trace:

```
Error: Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Closed, cause: None }) })
    at PrismaClientFetcher.request (/packages/amplication-server/node_modules/@prisma/client/runtime/index.js:1:228459)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
```

GraphQL Query:

```graphql
query builds($appId: String!) {
  builds(where: { app: { id: $appId } }, orderBy: { createdAt: Desc }) {
    id
    appId
    version
    message
    createdAt
    actionId
    createdBy {
      id
      account {
        firstName
        lastName
        __typename
      }
      __typename
    }
    status
    archiveURI
    __typename
  }
}
```

---

Stack Trace:

```
Error: Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Closed, cause: None }) })
    at PrismaClientFetcher.request (/packages/amplication-server/node_modules/@prisma/client/runtime/index.js:1:228459)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

GraphQL Query:

```graphql
query actionLog($actionId: String!) {
  action(where: { id: $actionId }) {
    id
    createdAt
    steps {
      id
      createdAt
      message
      status
      completedAt
      logs {
        id
        createdAt
        message
        meta
        level
        __typename
      }
      __typename
    }
    __typename
  }
}
```

---

Stack Trace:

```
Error: Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Closed, cause: None }) })
    at PrismaClientFetcher.request (/packages/amplication-server/node_modules/@prisma/client/runtime/index.js:1:228459)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

GraphQL Query:

```graphql
query actionLog($actionId: String!) {
  action(where: { id: $actionId }) {
    id
    createdAt
    steps {
      id
      createdAt
      message
      status
      completedAt
      logs {
        id
        createdAt
        message
        meta
        level
        __typename
      }
      __typename
    }
    __typename
  }
}
```

---

Stack Trace:

```
Error: Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Closed, cause: None }) })
    at PrismaClientFetcher.request (/packages/amplication-server/node_modules/@prisma/client/runtime/index.js:1:228459)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
```

GraphQL Query:

```graphql
query builds($appId: String!) {
  builds(where: { app: { id: $appId } }, orderBy: { createdAt: Desc }) {
    id
    appId
    version
    message
    createdAt
    actionId
    createdBy {
      id
      account {
        firstName
        lastName
        __typename
      }
      __typename
    }
    status
    archiveURI
    __typename
  }
}
```

---

Stack Trace:

```
Error: Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Closed, cause: None }) })
    at PrismaClientFetcher.request (/packages/amplication-server/node_modules/@prisma/client/runtime/index.js:1:228459)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

GraphQL Query:

```graphql
query actionLog($actionId: String!) {
  action(where: { id: $actionId }) {
    id
    createdAt
    steps {
      id
      createdAt
      message
      status
      completedAt
      logs {
        id
        createdAt
        message
        meta
        level
        __typename
      }
      __typename
    }
    __typename
  }
}
```

**Comment by yuval-hazaz** [comment]
@iddan, all errors of this type (9 total) happened in the same time (within 10 seconds) to the same client and never happened before or after this time frame.
It seems like a network or infra issue.
I suggest we close this issue and keep monitoring the logs
