### ISSUE TITLE
As a user - I'd like my generated service to not run as ROOT user in a container

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#5060]
Currently, each service generated by amplication contains a Dockerfile that will create an image running as root user.
Running containers with ‘root’ user can lead to a container escape situation. It is a best practice to run containers as non-root users, which can be done by adding a ‘USER’ statement to the Dockerfile.
 
We need to update the dsg to generate a service with a  Dockerfile like the following example:

```Dockerfile
FROM node:18.13.0-slim AS base

ARG component=<service-name>
ARG user=${component}}
ARG uid=1001
ARG gid=$uid

WORKDIR /workspace/packages/${user}

COPY ./dist/packages/amplication-${component}/package*.json .
RUN npm install --omit-dev

COPY ./dist/packages/amplication-${component} .

RUN groupadd --gid ${gid} ${user}
RUN useradd --uid ${uid} --gid ${gid} -m ${user}
RUN chown -R ${uid}:${gid} /workspace/packages/${user}

USER ${user}

ENV PORT=3333
EXPOSE $PORT

ENTRYPOINT ["node", "./main.js"]
```

_Originally posted by @overbit in https://github.com/amplication/amplication/pull/4694#discussion_r1085177543_
Related to #4895

**Comment by levivannoort** [comment]
> the client component differs from the others and requires different changes (which I am currently working on, so i will post the example for it here once done)

**Comment by levivannoort** [comment]
client version:

```Dockerfile
FROM nginx:1.22-alpine

ARG component=client
ARG user=nginx
ARG group=${user}

RUN apk add --update-cache nodejs

WORKDIR /app

COPY ./packages/amplication-${component}/configuration/nginx.conf /etc/nginx/nginx.conf
COPY ./packages/amplication-${component}/configuration/default.conf /etc/nginx/conf.d/default.conf
COPY ./dist/packages/amplication-${component} .

RUN chown -R nginx:nginx /app && chmod -R 755 /app && \
    chown -R nginx:nginx /var/cache/nginx && \
    chown -R nginx:nginx /var/log/nginx && \
    chown -R nginx:nginx /etc/nginx/conf.d && \
    chown -R nginx:nginx /etc/nginx/conf.d/default.conf

RUN touch /var/run/nginx.pid && \
    chown -R nginx:nginx /var/run/nginx.pid

USER ${user}

RUN chmod +x scripts/entrypoint.sh
ENTRYPOINT [ "/app/scripts/entrypoint.sh" ]

CMD ["nginx", "-g", "daemon off;"]
```

**Comment by levivannoort** [comment]
@overbit could you try to copy these files over to a generated application and try and run the components based on the new Dockerfiles.

**Comment by levivannoort** [comment]
After that QA it can be moved the next sprint where it will be merged into next.

**Comment by overbit** [comment]
Issue found when we are running the generated app from docker-compose.
With the change of only production dependencies, the migrate container will fail to run the `npm run seed` due to the Ts Error below:

```shell
2023-02-15 14:54:00 
2023-02-15 14:54:00 > @sample-application/server@0.1.3 db:init
2023-02-15 14:54:00 > run-s "db:migrate-save -- --name 'initial version'" db:migrate-up seed
2023-02-15 14:54:00 
2023-02-15 14:54:01 
2023-02-15 14:54:01 > @sample-application/server@0.1.3 db:migrate-save
2023-02-15 14:54:01 > prisma migrate dev --name initial version
2023-02-15 14:54:01 
2023-02-15 14:54:01 Prisma schema loaded from prisma/schema.prisma
2023-02-15 14:54:01 Datasource "postgres": PostgreSQL database "postgres", schema "public" at "db:5432"
2023-02-15 14:54:01 
2023-02-15 14:54:03 Applying migration `20230215145403_initial_version`
2023-02-15 14:54:03 
2023-02-15 14:54:03 The following migration(s) have been created and applied from new schema changes:
2023-02-15 14:54:03 
2023-02-15 14:54:03 migrations/
2023-02-15 14:54:03   └─ 20230215145403_initial_version/
2023-02-15 14:54:03     └─ migration.sql
2023-02-15 14:54:03 
2023-02-15 14:54:03 Your database is now in sync with your schema.
2023-02-15 14:54:03 
2023-02-15 14:54:03 Running generate... (Use --skip-generate to skip the generat
✔ Generated Prisma Client (4.6.1 | library) to ./node_modules/@prisma/client in 
2023-02-15 14:54:03 136ms
2023-02-15 14:54:03 
2023-02-15 14:54:03 
2023-02-15 14:54:04 
2023-02-15 14:54:04 > @sample-application/server@0.1.3 db:migrate-up
2023-02-15 14:54:04 > prisma migrate deploy
2023-02-15 14:54:04 
2023-02-15 14:54:04 Prisma schema loaded from prisma/schema.prisma
2023-02-15 14:54:04 Datasource "postgres": PostgreSQL database "postgres", schema "public" at "db:5432"
2023-02-15 14:54:04 
2023-02-15 14:54:04 1 migration found in prisma/migrations
2023-02-15 14:54:04 
2023-02-15 14:54:04 
2023-02-15 14:54:04 No pending migrations to apply.
2023-02-15 14:54:04 
2023-02-15 14:54:04 > @sample-application/server@0.1.3 seed
2023-02-15 14:54:04 > ts-node scripts/seed.ts
2023-02-15 14:54:04 
2023-02-15 14:54:06 
2023-02-15 14:54:06 /app/node_modules/ts-node/src/index.ts:513
2023-02-15 14:54:06     return new TSError(diagnosticText, diagnosticCodes)
2023-02-15 14:54:06            ^
2023-02-15 14:54:06 TSError: ⨯ Unable to compile TypeScript:
2023-02-15 14:54:06 scripts/seed.ts(5,22): error TS7016: Could not find a declaration file for module 'bcrypt'. '/app/node_modules/bcrypt/bcrypt.js' implicitly has an 'any' type.
2023-02-15 14:54:06   Try `npm i --save-dev @types/bcrypt` if it exists or add a new declaration (.d.ts) file containing `declare module 'bcrypt';`
2023-02-15 14:54:06 
2023-02-15 14:54:06     at createTSError (/app/node_modules/ts-node/src/index.ts:513:12)
2023-02-15 14:54:06     at reportTSError (/app/node_modules/ts-node/src/index.ts:517:19)
2023-02-15 14:54:06     at getOutput (/app/node_modules/ts-node/src/index.ts:752:36)
2023-02-15 14:54:06     at Object.compile (/app/node_modules/ts-node/src/index.ts:968:32)
2023-02-15 14:54:06     at Module.m._compile (/app/node_modules/ts-node/src/index.ts:1056:42)
2023-02-15 14:54:06     at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
2023-02-15 14:54:06     at Object.require.extensions.<computed> [as .ts] (/app/node_modules/ts-node/src/index.ts:1059:12)
2023-02-15 14:54:06     at Module.load (node:internal/modules/cjs/loader:1081:32)
2023-02-15 14:54:06     at Function.Module._load (node:internal/modules/cjs/loader:922:12)
2023-02-15 14:54:06     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
2023-02-15 14:54:06 ERROR: "seed" exited with 1.
2023-02-15 14:54:06 npm notice 
2023-02-15 14:54:06 npm notice New major version of npm available! 8.19.3 -> 9.4.2
2023-02-15 14:54:06 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.4.2>
2023-02-15 14:54:06 npm notice Run `npm install -g npm@9.4.2` to update!
2023-02-15 14:54:06 npm notice 

```

**Comment by levivannoort** [comment]
Quickest but not the most beautiful fix would be to move the `@types/bcrypt` from the devDependencies to the regular runtime dependencies. It does create a bigger image and introduces something that isnt actually used at runtime, but since we're currently using the same container image for doing the migration on the generated applications as well this would be the easiest.

This doesnt change current behaviour as at the moment the devDependencies werent ommitted from the runtime image. This problem came to light when enforcing a best practices.

**Comment by levivannoort** [comment]
As talked about during the standup, the quick solution will be done at this time.
