### ISSUE TITLE
🐛 Bug Report: Sending messages to Kafka fails during the first seconds of service running

### ISSUE THREAD

**Issue by EugeneTseitlin** [amplication/amplication#5083]
### What happened?

I've managed to reproduce it and after some code modification succeeded to extract error message:
error: Cannot read properties of null (reading 'send') {"service":"amplication-server","stack":"TypeError: Cannot read properties of null (reading 'send')\n at ClientKafka.dispatchEvent (/home/eugene/development/amplication/node_modules/@nestjs/microservices/client/client-kafka.js:131:30)","timestamp":"2023-01-25T14:47:04.372Z"}

/home/eugene/development/amplication/node_modules/@nestjs/microservices/client/client-kafka.js:131
return this.producer.send(message);
^
TypeError: Cannot read properties of null (reading 'send')
at ClientKafka.dispatchEvent (/home/eugene/development/amplication/node_modules/@nestjs/microservices/client/client-kafka.js:131:30)

What happens is that producer is simply not yet initialized when emit message occurs.

### What you expected to happen

Every message should be emitted to kafka without any exception.

### How to reproduce

Run amplication-server locally
During first seconds of running the service trigger sending messages to kafka, for example by creating builds for any project
You have to emit several messages in order to reproduce the issue
Now you should see that some of the messages were not actually emitted by checking build status and checking kafka topic
Be aware, that issue is not consistent, you may have to repeat the process couple of times to catch it

**Comment by EugeneTseitlin** [comment]
@overbit @abrl91 @tupe12334 @morhag90 @barshimi Please, feel free to share you opinion about the issue and possible solutions.

@levivannoort Is it possible to delay sending request to amplication-server from client? let's say after amplication-server pod answers positively on health check request, just to delay sending traffic to this pod for one minute. How does this sound?

**Comment by overbit** [comment]
@EugeneTseitlin we can then prove that this issue is actually related to https://github.com/nestjs/nest/issues/10449.

Regarding K8s we can adjust the initialDelaySeconds livenessProbe configuration  in conjunction with an health endpoint in each container. 

@EugeneTseitlin is there any out-of-the-box endpoint in nestjs that we can use to get the status of the runtime (like when all di are satisfied and the needed objects are instantiated) ?

**Comment by overbit** [comment]
Potentially fixed by #5399

**Comment by overbit** [comment]
Test result:
- status `PASSED` ✅  
- prove: https://jam.dev/c/089dc59c-a0d4-4cb4-b2c1-adcd25dd7384
