### ISSUE TITLE
🐛 Bug Report: Error in client right after start

### ISSUE THREAD

**Issue by EugeneTseitlin** [amplication/amplication#5180]
### What happened?

Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `WelcomePage_WelcomePage`.
    at createFiberFromTypeAndProps (react-dom.development.js:28439:1)
    at createFiberFromElement (react-dom.development.js:28465:1)
    at reconcileSingleElement (react-dom.development.js:15750:1)
    at reconcileChildFibers (react-dom.development.js:15808:1)
    at reconcileChildren (react-dom.development.js:19167:1)
    at updateHostComponent (react-dom.development.js:19924:1)
    at beginWork (react-dom.development.js:21618:1)
    at beginWork$1 (react-dom.development.js:27426:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
    at workLoopSync (react-dom.development.js:26466:1)

Here is an error that was received in browser console right after opening client app. 

### What you expected to happen

Client app should not crush with an exception.

### How to reproduce

In next branch
run server and client locally
open client app at http://localhost:3000
see the error

**Comment by overbit** [comment]
It seems related to this issue https://github.com/nrwl/nx/issues/14383
The fix has not been released yet but the latest beta already contains the fix

**Comment by abrl91** [comment]
tested in the sandbox environment:

https://user-images.githubusercontent.com/39680385/219014139-547b27b6-59e8-427d-a061-0136b769b75f.mov

and locally:


https://user-images.githubusercontent.com/39680385/219014225-a5985cd4-9f25-4385-b8be-90b3ed1ded28.mov
