### ISSUE TITLE
🐛 Bug Report: MongoDB Plugin Not Updating Service

### ISSUE THREAD

**Issue by MichaelSolati** [amplication/amplication#5345]
### What happened?

When attempting to commit and build Amplication after enabling MongoDB the PR has a conflict (with the swagger ts file) even though the GH project hasn't been touched at all.

### What you expected to happen

I expect the server to be configured to use mongodb.

### How to reproduce

Create a new project. Commit and build it. Then enable the MongoDB plugin, commit and build.

### Amplication version

1.3.5

**Comment by tupe12334** [comment]
While trying to run the plugin its fail with 
```
Error: ENOENT: no such file or directory, open '/Users/ofekgabay/Documents/git/amplication/packages/data-service-generator/amplication_modules/@amplication/plugin-db-mongo/dist/prisma_fmt_build_bg.wasm'
    at Object.openSync (node:fs:590:3)
    at Object.readFileSync (node:fs:458:35)
    at Object.23949 (webpack:///./node_modules/@prisma/prisma-fmt-wasm/src/prisma_fmt_build.js:604:41)
    at __webpack_require__ (webpack:///webpack/bootstrap:19:1)
    at Object.96071 (webpack:///./node_modules/@prisma/internals/dist/wasm.js:31:38)
    at __webpack_require__ (webpack:///webpack/bootstrap:19:1)
    at Object.24576 (webpack:///./node_modules/@prisma/internals/dist/engine-commands/formatSchema.js:35:19)
    at __webpack_require__ (webpack:///webpack/bootstrap:19:1)
    at Object.40773 (webpack:///./node_modules/@prisma/internals/dist/engine-commands/index.js:31:27)
    at __webpack_require__ (webpack:///webpack/bootstrap:19:1) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/ofekgabay/Documents/git/amplication/packages/data-service-generator/amplication_modules/@amplication/plugin-db-mongo/dist/prisma_fmt_build_bg.wasm'
}
```

The plugin have lib that is bundled into it that consumes `prisma_fmt_build_bg.wasm` file that does not exist in the context of the downloaded module
