### ISSUE TITLE
Kafka and zookeeper crash on local env

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#5448]
When I try to boot up Kafka and zookeeper in the new 7 versions https://github.com/amplication/amplication/pull/5036 both of them crash.

Kafka logs:
```
2023-03-16 09:54:43 ===> User
2023-03-16 09:54:43 uid=1000(appuser) gid=1000(appuser) groups=1000(appuser)
2023-03-16 09:54:43 ===> Configuring ...
2023-03-16 09:54:45 ===> Running preflight checks ... 
2023-03-16 09:54:45 ===> Check if /var/lib/kafka/data is writable ...
2023-03-16 09:54:45 ===> Check if Zookeeper is healthy ...
2023-03-16 09:54:46 [2023-03-16 07:54:46,076] INFO Client environment:zookeeper.version=3.6.3--6401e4ad2087061bc6b9f80dec2d69f2e3c8660a, built on 04/08/2021 16:35 GMT (org.apache.zookeeper.ZooKeeper)
2023-03-16 09:54:46 [2023-03-16 07:54:46,077] INFO Client environment:host.name=bb00ca9e5e1b (org.apache.zookeeper.ZooKeeper)
2023-03-16 09:54:46 [2023-03-16 07:54:46,077] INFO Client environment:java.version=11.0.17 (org.apache.zookeeper.ZooKeeper)
2023-03-16 09:54:46 [2023-03-16 07:54:46,077] INFO Client environment:java.vendor=Azul Systems, Inc. (org.apache.zookeeper.ZooKeeper)
2023-03-16 09:54:46 [2023-03-16 07:54:46,077] INFO Client environment:java.home=/usr/lib/jvm/zulu11-ca (org.apache.zookeeper.ZooKeeper)
2023-03-16 09:54:46 [2023-03-16 07:54:46,077] INFO Client environment:java.class.path=/usr/share/java/cp-base-new/kafka-server-common-7.3.1-ccs.jar:/usr/share/java/cp-base-new/jolokia-jvm-1.7.1.jar:/usr/share/java/cp-base-new/kafka-metadata-7.3.1-ccs.jar:/usr/share/java/cp-base-new/logredactor-1.0.10.jar:/usr/share/java/cp-base-new/kafka-raft-7.3.1-ccs.jar:/usr/share/java/cp-base-new/reload4j-1.2.19.jar:/usr/share/java/cp-base-new/argparse4j-0.7.0.jar:/usr/share/java/cp-base-new/metrics-core-4.1.12.1.jar:/usr/share/java/cp-base-new/disk-usage-agent-7.3.1.jar:/usr/share/java/cp-base-new/minimal-json-0.9.5.jar:/usr/share/java/cp-base-new/jackson-dataformat-csv-2.13.4.jar:/usr/share/java/cp-base-new/jackson-dataformat-yaml-2.13.4.jar:/usr/share/java/cp-base-new/slf4j-reload4j-1.7.36.jar:/usr/share/java/cp-base-new/jmx_prometheus_javaagent-0.17.2.jar:/usr/share/java/cp-base-new/common-utils-7.3.1.jar:/usr/share/java/cp-base-new/scala-reflect-2.13.10.jar:/usr/share/java/cp-base-new/commons-cli-1.4.jar:/usr/share/java/cp-base-new/zookeeper-jute-3.6.3.jar:/usr/share/java/cp-base-new/scala-library-2.13.10.jar:/usr/share/java/cp-base-new/lz4-java-1.8.0.jar:/usr/share/java/cp-base-new/re2j-1.6.jar:/usr/share/java/cp-base-new/scala-collection-compat_2.13-2.6.0.jar:/usr/share/java/cp-base-new/metrics-core-2.2.0.jar:/usr/share/java/cp-base-new/kafka-storage-api-7.3.1-ccs.jar:/usr/share/java/cp-base-new/jackson-module-scala_2.13-2.13.4.jar:/usr/share/java/cp-base-new/zstd-jni-1.5.2-1.jar:/usr/share/java/cp-base-new/slf4j-api-1.7.36.jar:/usr/share/java/cp-base-new/scala-java8-compat_2.13-1.0.2.jar:/usr/share/java/cp-base-new/kafka-storage-7.3.1-ccs.jar:/usr/share/java/cp-base-new/jopt-simple-5.0.4.jar:/usr/share/java/cp-base-new/paranamer-2.8.jar:/usr/share/java/cp-base-new/jolokia-core-1.7.1.jar:/usr/share/java/cp-base-new/jackson-databind-2.13.4.2.jar:/usr/share/java/cp-base-new/json-simple-1.1.1.jar:/usr/share/java/cp-base-new/jackson-datatype-jdk8-2.13.4.jar:/usr/share/java/cp-base-new/gson-2.9.0.jar:/usr/share/java/cp-base-new/snakeyaml-1.32.jar:/usr/share/java/cp-base-new/audience-annotations-0.5.0.jar:/usr/share/java/cp-base-new/jose4j-0.7.9.jar:/usr/share/java/cp-base-new/snappy-java-1.1.8.4.jar:/usr/share/java/cp-base-new/jackson-core-2.13.4.jar:/usr/share/java/cp-base-new/utility-belt-7.3.1.jar:/usr/share/java/cp-base-new/kafka_2.13-7.3.1-ccs.jar:/usr/share/java/cp-base-new/scala-logging_2.13-3.9.4.jar:/usr/share/java/cp-base-new/zookeeper-3.6.3.jar:/usr/share/java/cp-base-new/jackson-annotations-2.13.4.jar:/usr/share/java/cp-base-new/kafka-clients-7.3.1-ccs.jar:/usr/share/java/cp-base-new/logredactor-metrics-1.0.10.jar (org.apache.zookeeper.ZooKeeper)
2023-03-16 09:54:46 [2023-03-16 07:54:46,077] INFO Client environment:java.library.path=/usr/java/packages/lib:/lib:/usr/lib:/usr/lib64:/lib64 (org.apache.zookeeper.ZooKeeper)
2023-03-16 09:54:46 [2023-03-16 07:54:46,077] INFO Client environment:java.io.tmpdir=/tmp (org.apache.zookeeper.ZooKeeper)
2023-03-16 09:54:46 [2023-03-16 07:54:46,077] INFO Client environment:java.compiler=<NA> (org.apache.zookeeper.ZooKeeper)
2023-03-16 09:54:46 [2023-03-16 07:54:46,077] INFO Client environment:os.name=Linux (org.apache.zookeeper.ZooKeeper)
2023-03-16 09:54:46 [2023-03-16 07:54:46,077] INFO Client environment:os.arch=aarch64 (org.apache.zookeeper.ZooKeeper)
2023-03-16 09:54:46 [2023-03-16 07:54:46,077] INFO Client environment:os.version=5.15.49-linuxkit (org.apache.zookeeper.ZooKeeper)
2023-03-16 09:54:46 [2023-03-16 07:54:46,077] INFO Client environment:user.name=appuser (org.apache.zookeeper.ZooKeeper)
2023-03-16 09:54:46 [2023-03-16 07:54:46,077] INFO Client environment:user.home=/home/appuser (org.apache.zookeeper.ZooKeeper)
2023-03-16 09:54:46 [2023-03-16 07:54:46,077] INFO Client environment:user.dir=/home/appuser (org.apache.zookeeper.ZooKeeper)
2023-03-16 09:54:46 [2023-03-16 07:54:46,077] INFO Client environment:os.memory.free=69MB (org.apache.zookeeper.ZooKeeper)
2023-03-16 09:54:46 [2023-03-16 07:54:46,077] INFO Client environment:os.memory.max=1234MB (org.apache.zookeeper.ZooKeeper)
2023-03-16 09:54:46 [2023-03-16 07:54:46,077] INFO Client environment:os.memory.total=78MB (org.apache.zookeeper.ZooKeeper)
2023-03-16 09:54:46 [2023-03-16 07:54:46,081] INFO Initiating client connection, connectString=zookeeper:2181 sessionTimeout=40000 watcher=io.confluent.admin.utils.ZookeeperConnectionWatcher@516be40f (org.apache.zookeeper.ZooKeeper)
2023-03-16 09:54:46 [2023-03-16 07:54:46,090] INFO Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation (org.apache.zookeeper.common.X509Util)
2023-03-16 09:54:46 [2023-03-16 07:54:46,110] INFO jute.maxbuffer value is 1048575 Bytes (org.apache.zookeeper.ClientCnxnSocket)
2023-03-16 09:54:46 [2023-03-16 07:54:46,126] INFO zookeeper.request.timeout value is 0. feature enabled=false (org.apache.zookeeper.ClientCnxn)
2023-03-16 09:54:46 [2023-03-16 07:54:46,165] INFO Opening socket connection to server zookeeper/172.18.0.2:2181. (org.apache.zookeeper.ClientCnxn)
2023-03-16 09:54:46 [2023-03-16 07:54:46,166] INFO SASL config status: Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
2023-03-16 09:54:46 [2023-03-16 07:54:46,175] WARN Session 0x0 for sever zookeeper/172.18.0.2:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException. (org.apache.zookeeper.ClientCnxn)
2023-03-16 09:54:46 java.net.ConnectException: Connection refused
2023-03-16 09:54:46 at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
2023-03-16 09:54:46 at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
2023-03-16 09:54:46 at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:344)
2023-03-16 09:54:46 at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1290)
2023-03-16 09:54:47 [2023-03-16 07:54:47,280] INFO Opening socket connection to server zookeeper/172.18.0.2:2181. (org.apache.zookeeper.ClientCnxn)
2023-03-16 09:54:47 [2023-03-16 07:54:47,280] INFO SASL config status: Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
2023-03-16 10:09:08 [2023-03-16 08:09:08,645] ERROR Timed out waiting for connection to Zookeeper server [zookeeper:2181]. (io.confluent.admin.utils.ClusterStatus)
2023-03-16 10:09:08 [2023-03-16 08:09:08,828] WARN Client session timed out, have not heard from server in 40003ms for session id 0x0 (org.apache.zookeeper.ClientCnxn)
2023-03-16 10:09:08 [2023-03-16 08:09:08,829] WARN An exception was thrown while closing send thread for session 0x0. (org.apache.zookeeper.ClientCnxn)
2023-03-16 10:09:08 org.apache.zookeeper.ClientCnxn$SessionTimeoutException: Client session timed out, have not heard from server in 40003ms for session id 0x0
2023-03-16 10:09:08 at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1258)
2023-03-16 10:09:08 [2023-03-16 08:09:08,949] INFO Session: 0x0 closed (org.apache.zookeeper.ZooKeeper)
2023-03-16 10:09:08 Using log4j config /etc/kafka/log4j.properties
2023-03-16 10:29:50 ===> User
2023-03-16 10:29:50 uid=1000(appuser) gid=1000(appuser) groups=1000(appuser)
2023-03-16 10:29:50 ===> Configuring ...
2023-03-16 10:29:52 ===> Running preflight checks ... 
2023-03-16 10:29:52 ===> Check if /var/lib/kafka/data is writable ...
2023-03-16 10:29:52 ===> Check if Zookeeper is healthy ...
2023-03-16 10:29:53 [2023-03-16 08:29:53,023] INFO Client environment:zookeeper.version=3.6.3--6401e4ad2087061bc6b9f80dec2d69f2e3c8660a, built on 04/08/2021 16:35 GMT (org.apache.zookeeper.ZooKeeper)
2023-03-16 10:29:53 [2023-03-16 08:29:53,024] INFO Client environment:host.name=bb00ca9e5e1b (org.apache.zookeeper.ZooKeeper)
2023-03-16 10:29:53 [2023-03-16 08:29:53,024] INFO Client environment:java.version=11.0.17 (org.apache.zookeeper.ZooKeeper)
2023-03-16 10:29:53 [2023-03-16 08:29:53,024] INFO Client environment:java.vendor=Azul Systems, Inc. (org.apache.zookeeper.ZooKeeper)
2023-03-16 10:29:53 [2023-03-16 08:29:53,024] INFO Client environment:java.home=/usr/lib/jvm/zulu11-ca (org.apache.zookeeper.ZooKeeper)
2023-03-16 10:29:53 [2023-03-16 08:29:53,024] INFO Client environment:java.class.path=/usr/share/java/cp-base-new/kafka-server-common-7.3.1-ccs.jar:/usr/share/java/cp-base-new/jolokia-jvm-1.7.1.jar:/usr/share/java/cp-base-new/kafka-metadata-7.3.1-ccs.jar:/usr/share/java/cp-base-new/logredactor-1.0.10.jar:/usr/share/java/cp-base-new/kafka-raft-7.3.1-ccs.jar:/usr/share/java/cp-base-new/reload4j-1.2.19.jar:/usr/share/java/cp-base-new/argparse4j-0.7.0.jar:/usr/share/java/cp-base-new/metrics-core-4.1.12.1.jar:/usr/share/java/cp-base-new/disk-usage-agent-7.3.1.jar:/usr/share/java/cp-base-new/minimal-json-0.9.5.jar:/usr/share/java/cp-base-new/jackson-dataformat-csv-2.13.4.jar:/usr/share/java/cp-base-new/jackson-dataformat-yaml-2.13.4.jar:/usr/share/java/cp-base-new/slf4j-reload4j-1.7.36.jar:/usr/share/java/cp-base-new/jmx_prometheus_javaagent-0.17.2.jar:/usr/share/java/cp-base-new/common-utils-7.3.1.jar:/usr/share/java/cp-base-new/scala-reflect-2.13.10.jar:/usr/share/java/cp-base-new/commons-cli-1.4.jar:/usr/share/java/cp-base-new/zookeeper-jute-3.6.3.jar:/usr/share/java/cp-base-new/scala-library-2.13.10.jar:/usr/share/java/cp-base-new/lz4-java-1.8.0.jar:/usr/share/java/cp-base-new/re2j-1.6.jar:/usr/share/java/cp-base-new/scala-collection-compat_2.13-2.6.0.jar:/usr/share/java/cp-base-new/metrics-core-2.2.0.jar:/usr/share/java/cp-base-new/kafka-storage-api-7.3.1-ccs.jar:/usr/share/java/cp-base-new/jackson-module-scala_2.13-2.13.4.jar:/usr/share/java/cp-base-new/zstd-jni-1.5.2-1.jar:/usr/share/java/cp-base-new/slf4j-api-1.7.36.jar:/usr/share/java/cp-base-new/scala-java8-compat_2.13-1.0.2.jar:/usr/share/java/cp-base-new/kafka-storage-7.3.1-ccs.jar:/usr/share/java/cp-base-new/jopt-simple-5.0.4.jar:/usr/share/java/cp-base-new/paranamer-2.8.jar:/usr/share/java/cp-base-new/jolokia-core-1.7.1.jar:/usr/share/java/cp-base-new/jackson-databind-2.13.4.2.jar:/usr/share/java/cp-base-new/json-simple-1.1.1.jar:/usr/share/java/cp-base-new/jackson-datatype-jdk8-2.13.4.jar:/usr/share/java/cp-base-new/gson-2.9.0.jar:/usr/share/java/cp-base-new/snakeyaml-1.32.jar:/usr/share/java/cp-base-new/audience-annotations-0.5.0.jar:/usr/share/java/cp-base-new/jose4j-0.7.9.jar:/usr/share/java/cp-base-new/snappy-java-1.1.8.4.jar:/usr/share/java/cp-base-new/jackson-core-2.13.4.jar:/usr/share/java/cp-base-new/utility-belt-7.3.1.jar:/usr/share/java/cp-base-new/kafka_2.13-7.3.1-ccs.jar:/usr/share/java/cp-base-new/scala-logging_2.13-3.9.4.jar:/usr/share/java/cp-base-new/zookeeper-3.6.3.jar:/usr/share/java/cp-base-new/jackson-annotations-2.13.4.jar:/usr/share/java/cp-base-new/kafka-clients-7.3.1-ccs.jar:/usr/share/java/cp-base-new/logredactor-metrics-1.0.10.jar (org.apache.zookeeper.ZooKeeper)
2023-03-16 10:29:53 [2023-03-16 08:29:53,024] INFO Client environment:java.library.path=/usr/java/packages/lib:/lib:/usr/lib:/usr/lib64:/lib64 (org.apache.zookeeper.ZooKeeper)
2023-03-16 10:29:53 [2023-03-16 08:29:53,024] INFO Client environment:java.io.tmpdir=/tmp (org.apache.zookeeper.ZooKeeper)
2023-03-16 10:29:53 [2023-03-16 08:29:53,024] INFO Client environment:java.compiler=<NA> (org.apache.zookeeper.ZooKeeper)
2023-03-16 10:29:53 [2023-03-16 08:29:53,024] INFO Client environment:os.name=Linux (org.apache.zookeeper.ZooKeeper)
2023-03-16 10:29:53 [2023-03-16 08:29:53,024] INFO Client environment:os.arch=aarch64 (org.apache.zookeeper.ZooKeeper)
2023-03-16 10:29:53 [2023-03-16 08:29:53,024] INFO Client environment:os.version=5.15.49-linuxkit (org.apache.zookeeper.ZooKeeper)
2023-03-16 10:29:53 [2023-03-16 08:29:53,024] INFO Client environment:user.name=appuser (org.apache.zookeeper.ZooKeeper)
2023-03-16 10:29:53 [2023-03-16 08:29:53,024] INFO Client environment:user.home=/home/appuser (org.apache.zookeeper.ZooKeeper)
2023-03-16 10:29:53 [2023-03-16 08:29:53,024] INFO Client environment:user.dir=/home/appuser (org.apache.zookeeper.ZooKeeper)
2023-03-16 10:29:53 [2023-03-16 08:29:53,024] INFO Client environment:os.memory.free=69MB (org.apache.zookeeper.ZooKeeper)
2023-03-16 10:29:53 [2023-03-16 08:29:53,024] INFO Client environment:os.memory.max=1234MB (org.apache.zookeeper.ZooKeeper)
2023-03-16 10:29:53 [2023-03-16 08:29:53,024] INFO Client environment:os.memory.total=78MB (org.apache.zookeeper.ZooKeeper)
2023-03-16 10:29:53 [2023-03-16 08:29:53,027] INFO Initiating client connection, connectString=zookeeper:2181 sessionTimeout=40000 watcher=io.confluent.admin.utils.ZookeeperConnectionWatcher@516be40f (org.apache.zookeeper.ZooKeeper)
2023-03-16 10:29:53 [2023-03-16 08:29:53,029] INFO Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation (org.apache.zookeeper.common.X509Util)
2023-03-16 10:29:53 [2023-03-16 08:29:53,034] INFO jute.maxbuffer value is 1048575 Bytes (org.apache.zookeeper.ClientCnxnSocket)
2023-03-16 10:29:53 [2023-03-16 08:29:53,039] INFO zookeeper.request.timeout value is 0. feature enabled=false (org.apache.zookeeper.ClientCnxn)
2023-03-16 10:29:53 [2023-03-16 08:29:53,061] INFO Opening socket connection to server zookeeper/172.18.0.4:2181. (org.apache.zookeeper.ClientCnxn)
2023-03-16 10:29:53 [2023-03-16 08:29:53,062] INFO SASL config status: Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
2023-03-16 10:29:53 [2023-03-16 08:29:53,069] WARN Session 0x0 for sever zookeeper/172.18.0.4:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException. (org.apache.zookeeper.ClientCnxn)
2023-03-16 10:29:53 java.net.ConnectException: Connection refused
2023-03-16 10:29:53 at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
2023-03-16 10:29:53 at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
2023-03-16 10:29:53 at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:344)
2023-03-16 10:29:53 at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1290)
2023-03-16 10:29:54 [2023-03-16 08:29:54,172] INFO Opening socket connection to server zookeeper/172.18.0.4:2181. (org.apache.zookeeper.ClientCnxn)
2023-03-16 10:29:54 [2023-03-16 08:29:54,172] INFO SASL config status: Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
2023-03-16 10:30:33 [2023-03-16 08:30:33,043] ERROR Timed out waiting for connection to Zookeeper server [zookeeper:2181]. (io.confluent.admin.utils.ClusterStatus)
2023-03-16 10:30:33 [2023-03-16 08:30:33,184] WARN Client session timed out, have not heard from server in 40003ms for session id 0x0 (org.apache.zookeeper.ClientCnxn)
2023-03-16 10:30:33 [2023-03-16 08:30:33,184] WARN An exception was thrown while closing send thread for session 0x0. (org.apache.zookeeper.ClientCnxn)
2023-03-16 10:30:33 org.apache.zookeeper.ClientCnxn$SessionTimeoutException: Client session timed out, have not heard from server in 40003ms for session id 0x0
2023-03-16 10:30:33 at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1258)
2023-03-16 10:30:33 [2023-03-16 08:30:33,290] INFO Session: 0x0 closed (org.apache.zookeeper.ZooKeeper)
2023-03-16 10:30:33 [2023-03-16 08:30:33,290] INFO EventThread shut down for session: 0x0 (org.apache.zookeeper.ClientCnxn)
2023-03-16 10:30:33 Using log4j config /etc/kafka/log4j.properties
2023-03-16 16:07:23 ===> User
2023-03-16 16:07:23 uid=1000(appuser) gid=1000(appuser) groups=1000(appuser)
2023-03-16 16:07:23 ===> Configuring ...
2023-03-16 16:07:25 ===> Running preflight checks ... 
2023-03-16 16:07:25 ===> Check if /var/lib/kafka/data is writable ...
2023-03-16 16:07:25 ===> Check if Zookeeper is healthy ...
2023-03-16 16:07:26 [2023-03-16 14:07:26,123] INFO Client environment:zookeeper.version=3.6.3--6401e4ad2087061bc6b9f80dec2d69f2e3c8660a, built on 04/08/2021 16:35 GMT (org.apache.zookeeper.ZooKeeper)
2023-03-16 16:07:26 [2023-03-16 14:07:26,124] INFO Client environment:host.name=bb00ca9e5e1b (org.apache.zookeeper.ZooKeeper)
2023-03-16 16:07:26 [2023-03-16 14:07:26,124] INFO Client environment:java.version=11.0.17 (org.apache.zookeeper.ZooKeeper)
2023-03-16 16:07:26 [2023-03-16 14:07:26,124] INFO Client environment:java.vendor=Azul Systems, Inc. (org.apache.zookeeper.ZooKeeper)
2023-03-16 16:07:26 [2023-03-16 14:07:26,124] INFO Client environment:java.home=/usr/lib/jvm/zulu11-ca (org.apache.zookeeper.ZooKeeper)
2023-03-16 16:07:26 [2023-03-16 14:07:26,124] INFO Client environment:java.class.path=/usr/share/java/cp-base-new/kafka-server-common-7.3.1-ccs.jar:/usr/share/java/cp-base-new/jolokia-jvm-1.7.1.jar:/usr/share/java/cp-base-new/kafka-metadata-7.3.1-ccs.jar:/usr/share/java/cp-base-new/logredactor-1.0.10.jar:/usr/share/java/cp-base-new/kafka-raft-7.3.1-ccs.jar:/usr/share/java/cp-base-new/reload4j-1.2.19.jar:/usr/share/java/cp-base-new/argparse4j-0.7.0.jar:/usr/share/java/cp-base-new/metrics-core-4.1.12.1.jar:/usr/share/java/cp-base-new/disk-usage-agent-7.3.1.jar:/usr/share/java/cp-base-new/minimal-json-0.9.5.jar:/usr/share/java/cp-base-new/jackson-dataformat-csv-2.13.4.jar:/usr/share/java/cp-base-new/jackson-dataformat-yaml-2.13.4.jar:/usr/share/java/cp-base-new/slf4j-reload4j-1.7.36.jar:/usr/share/java/cp-base-new/jmx_prometheus_javaagent-0.17.2.jar:/usr/share/java/cp-base-new/common-utils-7.3.1.jar:/usr/share/java/cp-base-new/scala-reflect-2.13.10.jar:/usr/share/java/cp-base-new/commons-cli-1.4.jar:/usr/share/java/cp-base-new/zookeeper-jute-3.6.3.jar:/usr/share/java/cp-base-new/scala-library-2.13.10.jar:/usr/share/java/cp-base-new/lz4-java-1.8.0.jar:/usr/share/java/cp-base-new/re2j-1.6.jar:/usr/share/java/cp-base-new/scala-collection-compat_2.13-2.6.0.jar:/usr/share/java/cp-base-new/metrics-core-2.2.0.jar:/usr/share/java/cp-base-new/kafka-storage-api-7.3.1-ccs.jar:/usr/share/java/cp-base-new/jackson-module-scala_2.13-2.13.4.jar:/usr/share/java/cp-base-new/zstd-jni-1.5.2-1.jar:/usr/share/java/cp-base-new/slf4j-api-1.7.36.jar:/usr/share/java/cp-base-new/scala-java8-compat_2.13-1.0.2.jar:/usr/share/java/cp-base-new/kafka-storage-7.3.1-ccs.jar:/usr/share/java/cp-base-new/jopt-simple-5.0.4.jar:/usr/share/java/cp-base-new/paranamer-2.8.jar:/usr/share/java/cp-base-new/jolokia-core-1.7.1.jar:/usr/share/java/cp-base-new/jackson-databind-2.13.4.2.jar:/usr/share/java/cp-base-new/json-simple-1.1.1.jar:/usr/share/java/cp-base-new/jackson-datatype-jdk8-2.13.4.jar:/usr/share/java/cp-base-new/gson-2.9.0.jar:/usr/share/java/cp-base-new/snakeyaml-1.32.jar:/usr/share/java/cp-base-new/audience-annotations-0.5.0.jar:/usr/share/java/cp-base-new/jose4j-0.7.9.jar:/usr/share/java/cp-base-new/snappy-java-1.1.8.4.jar:/usr/share/java/cp-base-new/jackson-core-2.13.4.jar:/usr/share/java/cp-base-new/utility-belt-7.3.1.jar:/usr/share/java/cp-base-new/kafka_2.13-7.3.1-ccs.jar:/usr/share/java/cp-base-new/scala-logging_2.13-3.9.4.jar:/usr/share/java/cp-base-new/zookeeper-3.6.3.jar:/usr/share/java/cp-base-new/jackson-annotations-2.13.4.jar:/usr/share/java/cp-base-new/kafka-clients-7.3.1-ccs.jar:/usr/share/java/cp-base-new/logredactor-metrics-1.0.10.jar (org.apache.zookeeper.ZooKeeper)
2023-03-16 16:07:26 [2023-03-16 14:07:26,124] INFO Client environment:java.library.path=/usr/java/packages/lib:/lib:/usr/lib:/usr/lib64:/lib64 (org.apache.zookeeper.ZooKeeper)
2023-03-16 16:07:26 [2023-03-16 14:07:26,124] INFO Client environment:java.io.tmpdir=/tmp (org.apache.zookeeper.ZooKeeper)
2023-03-16 16:07:26 [2023-03-16 14:07:26,124] INFO Client environment:java.compiler=<NA> (org.apache.zookeeper.ZooKeeper)
2023-03-16 16:07:26 [2023-03-16 14:07:26,124] INFO Client environment:os.name=Linux (org.apache.zookeeper.ZooKeeper)
2023-03-16 16:07:26 [2023-03-16 14:07:26,124] INFO Client environment:os.arch=aarch64 (org.apache.zookeeper.ZooKeeper)
2023-03-16 16:07:26 [2023-03-16 14:07:26,124] INFO Client environment:os.version=5.15.49-linuxkit (org.apache.zookeeper.ZooKeeper)
2023-03-16 16:07:26 [2023-03-16 14:07:26,124] INFO Client environment:user.name=appuser (org.apache.zookeeper.ZooKeeper)
2023-03-16 16:07:26 [2023-03-16 14:07:26,124] INFO Client environment:user.home=/home/appuser (org.apache.zookeeper.ZooKeeper)
2023-03-16 16:07:26 [2023-03-16 14:07:26,124] INFO Client environment:user.dir=/home/appuser (org.apache.zookeeper.ZooKeeper)
2023-03-16 16:07:26 [2023-03-16 14:07:26,124] INFO Client environment:os.memory.free=69MB (org.apache.zookeeper.ZooKeeper)
2023-03-16 16:07:26 [2023-03-16 14:07:26,124] INFO Client environment:os.memory.max=1234MB (org.apache.zookeeper.ZooKeeper)
2023-03-16 16:07:26 [2023-03-16 14:07:26,124] INFO Client environment:os.memory.total=78MB (org.apache.zookeeper.ZooKeeper)
2023-03-16 16:07:26 [2023-03-16 14:07:26,127] INFO Initiating client connection, connectString=zookeeper:2181 sessionTimeout=40000 watcher=io.confluent.admin.utils.ZookeeperConnectionWatcher@516be40f (org.apache.zookeeper.ZooKeeper)
2023-03-16 16:07:26 [2023-03-16 14:07:26,131] INFO Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation (org.apache.zookeeper.common.X509Util)
2023-03-16 16:07:26 [2023-03-16 14:07:26,137] INFO jute.maxbuffer value is 1048575 Bytes (org.apache.zookeeper.ClientCnxnSocket)
2023-03-16 16:07:26 [2023-03-16 14:07:26,143] INFO zookeeper.request.timeout value is 0. feature enabled=false (org.apache.zookeeper.ClientCnxn)
2023-03-16 16:07:26 [2023-03-16 14:07:26,165] INFO Opening socket connection to server zookeeper/172.18.0.4:2181. (org.apache.zookeeper.ClientCnxn)
2023-03-16 16:07:26 [2023-03-16 14:07:26,166] INFO SASL config status: Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
2023-03-16 16:07:26 [2023-03-16 14:07:26,174] WARN Session 0x0 for sever zookeeper/172.18.0.4:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException. (org.apache.zookeeper.ClientCnxn)
2023-03-16 16:07:26 java.net.ConnectException: Connection refused
2023-03-16 16:07:26 at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
2023-03-16 16:07:26 at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
2023-03-16 16:07:26 at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:344)
2023-03-16 16:07:26 at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1290)
2023-03-16 16:07:27 [2023-03-16 14:07:27,279] INFO Opening socket connection to server zookeeper/172.18.0.4:2181. (org.apache.zookeeper.ClientCnxn)
2023-03-16 16:07:27 [2023-03-16 14:07:27,279] INFO SASL config status: Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
2023-03-16 16:08:06 [2023-03-16 14:08:06,157] ERROR Timed out waiting for connection to Zookeeper server [zookeeper:2181]. (io.confluent.admin.utils.ClusterStatus)
2023-03-16 16:08:06 [2023-03-16 14:08:06,302] WARN Client session timed out, have not heard from server in 40001ms for session id 0x0 (org.apache.zookeeper.ClientCnxn)
2023-03-16 16:08:06 [2023-03-16 14:08:06,302] WARN An exception was thrown while closing send thread for session 0x0. (org.apache.zookeeper.ClientCnxn)
2023-03-16 16:08:06 org.apache.zookeeper.ClientCnxn$SessionTimeoutException: Client session timed out, have not heard from server in 40001ms for session id 0x0
2023-03-16 16:08:06 at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1258)
2023-03-16 16:08:06 [2023-03-16 14:08:06,412] INFO Session: 0x0 closed (org.apache.zookeeper.ZooKeeper)
2023-03-16 16:08:06 [2023-03-16 14:08:06,412] INFO EventThread shut down for session: 0x0 (org.apache.zookeeper.ClientCnxn)
2023-03-16 16:08:06 Using log4j config /etc/kafka/log4j.properties
```

**Comment by overbit** [comment]
Please @tupe12334 add more details like version of the docker engine, and state of the docker stack (fresh create or restart?).

**Comment by tupe12334** [comment]
@overbit after your question, I tried to remove the volume of the docker container, and its fixed the problem. Thanks.
