### ISSUE TITLE
🐛 Bug Report: Can't run plugin API locally

### ISSUE THREAD

**Issue by EugeneTseitlin** [amplication/amplication#5683]
### What happened?

Here is the error that fails in amplication-plugin-api during `npx nx refresh:plugins amplication-plugin-api`:
githubCatalogPlugins Error: Could not find mapping for model Plugin
    at Wr.createMessage (/home/eugene/development/amplication/dist/packages/amplication-plugin-api/webpack:/amplication/packages/amplication-plugin-api/prisma/generated-prisma-client/runtime/library.js:164:13251)
    at /home/eugene/development/amplication/dist/packages/amplication-plugin-api/webpack:/amplication/packages/amplication-plugin-api/prisma/generated-prisma-client/runtime/library.js:174:10933
    at /home/eugene/development/amplication/dist/packages/amplication-plugin-api/webpack:/amplication/packages/amplication-plugin-api/prisma/generated-prisma-client/runtime/library.js:70:25817
    at Generator.next (<anonymous>)
    at /home/eugene/development/amplication/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/eugene/development/amplication/node_modules/tslib/tslib.js:163:16)
    at runInChildSpan (/home/eugene/development/amplication/dist/packages/amplication-plugin-api/main.js:2943:20)
    at PrismaService.<anonymous> (/home/eugene/development/amplication/dist/packages/amplication-plugin-api/webpack:/amplication/packages/amplication-plugin-api/prisma/generated-prisma-client/runtime/library.js:174:10922)
    at Generator.next (<anonymous>) {
  clientVersion: '4.11.0'

### What you expected to happen

plugin import should work

### How to reproduce

run amplication-plugin-api
run `npx nx refresh:plugins amplication-plugin-api`
see the error in amplication-plugin-api logs

### Environment

locally

**Comment by GreenMachine01** [comment]
@EugeneTseitlin is this bug still relevant?

**Comment by DanielHritcu** [comment]
@GreenMachine01 yes

**Comment by overbit** [comment]
Raised a new issue to help to debug  #6004
