### ISSUE TITLE
🐛 Bug Report: `src/user/base/user.controller.base.spec.ts` test fails

### ISSUE THREAD

**Issue by levivannoort** [amplication/amplication#5924]
### What happened?

```
levi@sld three-three % npm test

> test
> jest

 PASS  src/providers/secrets/base/secretsManager.service.base.spec.ts (6.068 s)
 PASS  src/validators/is-json-value-validator.spec.ts (6.25 s)
 PASS  src/auth/password.service.spec.ts (6.324 s)
 PASS  src/tests/health/health.service.spec.ts (6.352 s)
 PASS  src/tests/auth/token.service.spec.ts (6.361 s)
 PASS  src/prisma.util.spec.ts
 PASS  src/tests/auth/jwt/jwt.strategy.spec.ts
 PASS  src/auth/auth.service.spec.ts (6.821 s)
 FAIL  src/user/base/user.controller.base.spec.ts
  ● Test suite failed to run

    Cannot find module '@app/custom-validators' from 'src/user/base/UserCreateInput.ts'

    Require stack:
      src/user/base/UserCreateInput.ts
      src/user/base/user.controller.base.ts
      src/user/user.controller.ts
      src/user/base/user.controller.base.spec.ts

      13 | import { ApiProperty } from "@nestjs/swagger";
      14 | import { IsString, IsOptional } from "class-validator";
    > 15 | import { IsJSONValue } from "@app/custom-validators";
         | ^
      16 | import { GraphQLJSON } from "graphql-type-json";
      17 | import { InputJsonValue } from "../../types";
      18 |

      at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.<anonymous> (src/user/base/UserCreateInput.ts:15:1)

Test Suites: 1 failed, 8 passed, 9 total
Tests:       25 passed, 25 total
Snapshots:   0 total
Time:        7.743 s
Ran all test suites.
```

### What you expected to happen

I would expect all of the test to pass on the generated application.

### How to reproduce

Generate a new service and do an `npm install` and subsequently `npm test`

### Amplication version

1.5.5

**Comment by morhag90** [comment]
Passed QA:

<img width="1254" alt="image" src="https://github.com/amplication/amplication/assets/97830649/1a411b49-d827-43d4-bdf1-a594b2bd3576">
