### ISSUE TITLE
🐛 Bug Report: Mongo Plugin Fails During Seed

### ISSUE THREAD

**Issue by MichaelSolati** [amplication/amplication#5956]
### What happened?

When trying to run a service locally using MongoDB, the `npm run db:init` script fails.

```console
michaelsolati@DESKTOP-5UJ6QMA:~/workspace/todo-app-may/apps/todo-service$ npm run db:init

> db:init
> run-s seed


> seed
> ts-node scripts/seed.ts

Seeding database...
PrismaClientInitializationError: 
Invalid `client.user.upsert()` invocation in
/home/michaelsolati/workspace/todo-app-may/apps/todo-service/scripts/seed.ts:34:21

  31   roles: ["user"],
  32 };
  33 
→ 34 await client.user.upsert(
Database error. error code: unknown, error message: Server selection timeout: None of the available servers suitable for criteria Predicate. Topology: { Type: Unknown, Servers: [ { Address: localhost:27017, Type: RsGhost, Average RTT: 558.892µs, Last Update Time: DateTime(OffsetDateTime { local_datetime: PrimitiveDateTime { date: Date { year: 2023, ordinal: 130 }, time: Time { hour: 15, minute: 55, second: 48, nanosecond: 637000000 } }, offset: UtcOffset { hours: 0, minutes: 0, seconds: 0 } }), Max Wire Version: 17, Min Wire Version: 0 }, ] }
    at RequestHandler.handleRequestError (/home/michaelsolati/workspace/todo-app-may/apps/todo-service/node_modules/@prisma/client/runtime/index.js:34316:13)
    at RequestHandler.request (/home/michaelsolati/workspace/todo-app-may/apps/todo-service/node_modules/@prisma/client/runtime/index.js:34293:12)
    at async PrismaClient._request (/home/michaelsolati/workspace/todo-app-may/apps/todo-service/node_modules/@prisma/client/runtime/index.js:35273:16)
    at async seed (/home/michaelsolati/workspace/todo-app-may/apps/todo-service/scripts/seed.ts:34:3) {
  clientVersion: '4.6.1',
  errorCode: undefined
}
ERROR: "seed" exited with 1.
```

### What you expected to happen

I expect to be able to run the setup scripts in the readme.

### How to reproduce

Create a service with MongoDB and Auth Module. Run locally.

### Amplication version

1.5.6

**Comment by MichaelSolati** [comment]
Heads up, switching to Postgres works just fine.
