### ISSUE TITLE
🐛 Bug Report: Plugin api fails to update the packages

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#6012]
### What happened?

Running the `processPluginCatalog` mutation returns the following error

```graphql
{
  "errors": [
    {
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "processPluginCatalog"
      ],
      "extensions": {
        "extensions": {
          "code": "SOMETHING_BAD_HAPPENED",
          "http": {
            "status": 400
          }
        },
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "GraphQLError",
            "    at PluginResolver.<anonymous> (/workspace/packages/amplication-plugin-api/main.js:1:361824)",
            "    at Generator.throw (<anonymous>)",
            "    at rejected (/workspace/packages/amplication-plugin-api/node_modules/tslib/tslib.js:165:69)",
            "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
          ]
        }
      }
    }
  ],
  "data": {
    "processPluginCatalog": null
  }
}
```

### What you expected to happen

Plugins and their version to be successfully updated in the catalague

### How to reproduce

Make a graphql request with the following mutation
```
mutation{
   processPluginCatalog{
    name
    versions{
      pluginIdVersion
    }
  }
}
```

**Comment by overbit** [comment]
This is potentially related to rate shaping of Github and npm registry API

**Comment by overbit** [comment]
This is a blocker for #5852 and #5851
