### ISSUE TITLE
🐛 Bug Report: `plugin-swagger-apibody` is failing when installed in a service with `auth`

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#6143]
### What happened?

Installing `plugin-swagger-apibody` plugin in a service with authentication plugins installed will result in a broken build.

Logs
```
log_processed.buildId | clia5zc23002yfj0165ps2ml7
-- | --
log_processed.component | data-service-generator
log_processed.errorMessage | Failed to execute plugin event CreateEntityControllerBase. Could not find class declaration with the identifier UserControllerBase in provided AST node
log_processed.event | CreateServer
log_processed.level | error
log_processed.message | Failed to execute plugin event CreateServer. Failed to execute plugin event CreateEntityControllerBase. Could not find class declaration with the identifier UserControllerBase in provided AST node
log_processed.resourceId | cli1oot2701waex01e8ve6b6q
log_processed.stack | Error: Failed to execute plugin event CreateEntityControllerBase. Could not find class declaration with the identifier UserControllerBase in provided AST node    at getClassDeclarationById (/workspace/packages/data-service-generator/amplication_modules/@amplication/plugin-swagger-apibody/dist/index.js:20600:15)    at beforeCreateControllerBase (/workspace/packages/data-service-generator/amplication_modules/@amplication/plugin-swagger-apibody/dist/index.js:21202:68)    at /workspace/packages/data-service-generator/src/plugin-wrapper.js:7:152    at Generator.next (<anonymous>)    at fulfilled (/workspace/packages/data-service-generator/node_modules/tslib/tslib.js:164:62)


```

### What you expected to happen

 `plugin-swagger-apibody` plugin to run successfully regardless the auth plugins status

### How to reproduce

1. create a new service
2. install the  `plugin-swagger-apibody` plugin
3. install the `plugin-auth-core` and `plugin-auth-basic` or `plugin-auth-jwt`
4. build and observe

### Amplication version

v1.6.5

**Comment by mulygottlieb** [comment]
Fixed in https://github.com/amplication/plugins/pull/127
