### ISSUE TITLE
🐛 Bug Report: `Swagger ApiBody` plugin fails on newly generated services

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#6348]
### What happened?

log_processed.message | Failed to execute plugin event CreateServer. Failed to execute plugin event CreateEntityControllerBase. Could not find class declaration with the identifier UserControllerBase in provided AST node
-- | --
log_processed.resourceId | clj5wqo3h003wjp01tlho82i0
log_processed.stack | Error: Failed to execute plugin event CreateEntityControllerBase. Could not find class declaration with the identifier UserControllerBase in provided AST node    at getClassDeclarationById (/workspace/packages/data-service-generator/amplication_modules/@amplication/plugin-swagger-apibody/dist/index.js:20600:15)    at beforeCreateControllerBase (/workspace/packages/data-service-generator/amplication_modules/@amplication/plugin-swagger-apibody/dist/index.js:21202:68)    at /workspace/packages/data-service-generator/src/plugin-wrapper.js:7:152    at Generator.next (<anonymous>)    at fulfilled (/workspace/packages/data-service-generator/node_modules/tslib/tslib.js:164:62)

### What you expected to happen

Code to be generated successfully

### How to reproduce

TODO

### Amplication version

v1.7.6

**Comment by overbit** [comment]
Duplicate of #6143
