### ISSUE TITLE
🐛 Bug Report: RESTApi only generated services error on start 

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#6658]
### What happened?

```sh
[
  GraphQLError [Object]: Query root type must be provided.
      at SchemaValidationContext.reportError (/Users/daniele/workspace/otel-workshop/apps/ecommerce/node_modules/graphql/type/validate.js:86:19)
      at validateRootTypes (/Users/daniele/workspace/otel-workshop/apps/ecommerce/node_modules/graphql/type/validate.js:105:13)
      at validateSchema (/Users/daniele/workspace/otel-workshop/apps/ecommerce/node_modules/graphql/type/validate.js:50:3)
      at graphqlImpl (/Users/daniele/workspace/otel-workshop/apps/ecommerce/node_modules/graphql/graphql.js:79:62)
      at /Users/daniele/workspace/otel-workshop/apps/ecommerce/node_modules/graphql/graphql.js:28:59
      at new Promise (<anonymous>)
      at graphql (/Users/daniele/workspace/otel-workshop/apps/ecommerce/node_modules/graphql/graphql.js:26:10)
      at GraphQLSchemaFactory.create (/Users/daniele/workspace/otel-workshop/apps/ecommerce/node_modules/@nestjs/graphql/dist/schema-builder/graphql-schema.factory.js:48:60)
      at GraphQLSchemaBuilder.buildSchema (/Users/daniele/workspace/otel-workshop/apps/ecommerce/node_modules/@nestjs/graphql/dist/graphql-schema.builder.js:62:52)
      at GraphQLSchemaBuilder.build (/Users/daniele/workspace/otel-workshop/apps/ecommerce/node_modules/@nestjs/graphql/dist/graphql-schema.builder.js:24:31)
```

### What you expected to happen

Generated service to run successfully

### How to reproduce

1. Create a new service selecting only REST
2. Build
3. Try to run the generated app

### Amplication version

v1.8.5

**Comment by overbit** [comment]
It might be related to the fact that we generate the app module importing the GraphQlModule that should not be there at all.

**Comment by morhag90** [comment]
Passed QA:

<img width="1185" alt="image" src="https://github.com/amplication/amplication/assets/97830649/984e8b96-a236-4471-a7a4-7ff30956f3ae">
