### ISSUE TITLE
🐛 Bug Report: Refreshing the build log page loads an empty page

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#7107]
When you are viewing the build log and refresh the page, you get an empty page.
In the browser console you can notice the following error:

**vendor.377d5afcde73a9c9.js:102 Uncaught TypeError: Cannot read properties of undefined (reading 'build')**
    at Y (6963.152ad07c351a0044.js:1:2100)
    at Si (vendor.377d5afcde73a9c9.js:102:1435126)
    at Sl (vendor.377d5afcde73a9c9.js:102:1491981)
    at xc (vendor.377d5afcde73a9c9.js:102:1481133)
    at bc (vendor.377d5afcde73a9c9.js:102:1481061)
    at vc (vendor.377d5afcde73a9c9.js:102:1480924)
    at ic (vendor.377d5afcde73a9c9.js:102:1477731)
    at oc (vendor.377d5afcde73a9c9.js:102:1476283)
    at E (vendor.377d5afcde73a9c9.js:102:1728423)
    at M (vendor.377d5afcde73a9c9.js:102:1728955)

**Comment by mulygottlieb** [comment]
Passed QA
