### ISSUE TITLE
🐛 Bug Report: auth plugins cause failing build process. stack: AssertionError [ERR_ASSERTION]

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#7216]
### What happened?

While testing the auth-core plus either auth-jwt or auth-basic plugins, I discovered that the code generation fails with the following errors:

```sh
[data-service-generator] info 2023-10-10T15:10:27.115Z Running locally, skipping log reporting Module server/src/organization/base/CustomerUpdateManyWithoutOrganizationsInput.ts already exists. Overwriting... { resourceId: undefined, buildId: undefined }
[data-service-generator] info 2023-10-10T15:10:27.213Z Creating resources... { resourceId: undefined, buildId: undefined }
[data-service-generator] info 2023-10-10T15:10:27.214Z Running locally, skipping log reporting Creating resources... { resourceId: undefined, buildId: undefined }
[data-service-generator] info 2023-10-10T15:10:27.214Z Creating User... { resourceId: undefined, buildId: undefined }
[data-service-generator] info 2023-10-10T15:10:27.214Z Running locally, skipping log reporting Creating User... { resourceId: undefined, buildId: undefined }
[data-service-generator] error 2023-10-10T15:10:27.262Z Failed to execute plugin event CreateEntityServiceBase. The expression evaluated to a falsy value:
  assert_1.default.ok(lines instanceof linesModule.Lines)
 { generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==',
  errorMessage:
   'The expression evaluated to a falsy value:\n\n  assert_1.default.ok(lines instanceof linesModule.Lines)\n',
  event: 'CreateEntityServiceBase',
  resourceId: undefined,
  buildId: undefined,
  stack:
   'AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:\n\n  assert_1.default.ok(lines instanceof linesModule.Lines)\n\n    at new Patcher (/Users/user/workspace/amplication/amplication/node_modules/recast/lib/patcher.js:20:22)\n    at /Users/user/workspace/amplication/amplication/node_modules/recast/lib/patcher.js:138:23\n    at print (/Users/user/workspace/amplication/amplication/node_modules/recast/lib/printer.js:76:17)\n    at /Users/user/workspace/amplication/amplication/node_modules/recast/lib/printer.js:49:41\n    at Object.printComments (/Users/user/workspace/amplication/amplication/node_modules/recast/lib/comments.js:281:22)\n    at print (/Users/user/workspace/amplication/amplication/node_modules/recast/lib/printer.js:55:31)\n    at /Users/user/workspace/amplication/amplication/node_modules/recast/lib/printer.js:49:41\n    at FastPath.call (/Users/user/workspace/amplication/amplication/node_modules/recast/lib/fast-path.js:125:18)\n    at genericPrintNoParens (/Users/user/workspace/amplication/amplication/node_modules/recast/lib/printer.js:244:22)\n    at genericPrint (/Users/user/workspace/amplication/amplication/node_modules/recast/lib/printer.js:123:30)',
  cause: undefined }
[data-service-generator] error 2023-10-10T15:10:27.262Z Failed to execute plugin event CreateEntityServiceBase. The expression evaluated to a falsy value:
  assert_1.default.ok(lines instanceof linesModule.Lines)
 { resourceId: undefined, buildId: undefined, event: 'CreateEntityServiceBase' }
[data-service-generator] info 2023-10-10T15:10:27.262Z Running locally, skipping log reporting Failed to execute plugin event CreateEntityServiceBase. The expression evaluated to a falsy value:
  assert_1.default.ok(lines instanceof linesModule.Lines)
 { resourceId: undefined, buildId: undefined }
[data-service-generator] error 2023-10-10T15:10:27.262Z Failed to execute plugin event CreateServer. Failed to execute plugin event CreateEntityServiceBase. The expression evaluated to a falsy value:
  assert_1.default.ok(lines instanceof linesModule.Lines)
 { generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==',
  errorMessage:
   'Failed to execute plugin event CreateEntityServiceBase. The expression evaluated to a falsy value:\n\n  assert_1.default.ok(lines instanceof linesModule.Lines)\n',
  event: 'CreateServer',
  resourceId: undefined,
  buildId: undefined,
  stack:
   'AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:\n\n  assert_1.default.ok(lines instanceof linesModule.Lines)\n\n    at new Patcher (/Users/user/workspace/amplication/amplication/node_modules/recast/lib/patcher.js:20:22)\n    at /Users/user/workspace/amplication/amplication/node_modules/recast/lib/patcher.js:138:23\n    at print (/Users/user/workspace/amplication/amplication/node_modules/recast/lib/printer.js:76:17)\n    at /Users/user/workspace/amplication/amplication/node_modules/recast/lib/printer.js:49:41\n    at Object.printComments (/Users/user/workspace/amplication/amplication/node_modules/recast/lib/comments.js:281:22)\n    at print (/Users/user/workspace/amplication/amplication/node_modules/recast/lib/printer.js:55:31)\n    at /Users/user/workspace/amplication/amplication/node_modules/recast/lib/printer.js:49:41\n    at FastPath.call (/Users/user/workspace/amplication/amplication/node_modules/recast/lib/fast-path.js:125:18)\n    at genericPrintNoParens (/Users/user/workspace/amplication/amplication/node_modules/recast/lib/printer.js:244:22)\n    at genericPrint (/Users/user/workspace/amplication/amplication/node_modules/recast/lib/printer.js:123:30)',
  cause: undefined }
[data-service-generator] error 2023-10-10T15:10:27.263Z Failed to execute plugin event CreateServer. Failed to execute plugin event CreateEntityServiceBase. The expression evaluated to a falsy value:
  assert_1.default.ok(lines instanceof linesModule.Lines)
 { resourceId: undefined, buildId: undefined, event: 'CreateServer' }
[data-service-generator] info 2023-10-10T15:10:27.263Z Running locally, skipping log reporting Failed to execute plugin event CreateServer. Failed to execute plugin event CreateEntityServiceBase. The expression evaluated to a falsy value:
  assert_1.default.ok(lines instanceof linesModule.Lines)
 { resourceId: undefined, buildId: undefined }
[data-service-generator] error 2023-10-10T15:10:27.262Z Failed to run createDataService { generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==',
  errorMessage: undefined,
  event: 'CreateServer',
  resourceId: undefined,
  buildId: undefined }
[data-service-generator] error 2023-10-10T15:10:27.263Z Failed to run createDataService { resourceId: undefined, buildId: undefined }
[data-service-generator] error 2023-10-10T15:10:27.262Z Failed to execute plugin event CreateServer. Failed to execute plugin event CreateEntityServiceBase. The expression evaluated to a falsy value:
  assert_1.default.ok(lines instanceof linesModule.Lines)
 { generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==',
  errorMessage:
   'Failed to execute plugin event CreateEntityServiceBase. The expression evaluated to a falsy value:\n\n  assert_1.default.ok(lines instanceof linesModule.Lines)\n',
  event: 'CreateServer',
  resourceId: undefined,
  buildId: undefined,
  stack:
   'AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:\n\n  assert_1.default.ok(lines instanceof linesModule.Lines)\n\n    at new Patcher (/Users/user/workspace/amplication/amplication/node_modules/recast/lib/patcher.js:20:22)\n    at /Users/user/workspace/amplication/amplication/node_modules/recast/lib/patcher.js:138:23\n    at print (/Users/user/workspace/amplication/amplication/node_modules/recast/lib/printer.js:76:17)\n    at /Users/user/workspace/amplication/amplication/node_modules/recast/lib/printer.js:49:41\n    at Object.printComments (/Users/user/workspace/amplication/amplication/node_modules/recast/lib/comments.js:281:22)\n    at print (/Users/user/workspace/amplication/amplication/node_modules/recast/lib/printer.js:55:31)\n    at /Users/user/workspace/amplication/amplication/node_modules/recast/lib/printer.js:49:41\n    at FastPath.call (/Users/user/workspace/amplication/amplication/node_modules/recast/lib/fast-path.js:125:18)\n    at genericPrintNoParens (/Users/user/workspace/amplication/amplication/node_modules/recast/lib/printer.js:244:22)\n    at genericPrint (/Users/user/workspace/amplication/amplication/node_modules/recast/lib/printer.js:123:30)',
  cause: undefined }
[data-service-generator] error 2023-10-10T15:10:27.263Z Failed to execute plugin event CreateServer. Failed to execute plugin event CreateEntityServiceBase. The expression evaluated to a falsy value:
  assert_1.default.ok(lines instanceof linesModule.Lines)
 { resourceId: undefined, buildId: undefined }
[data-service-generator] info 2023-10-10T15:10:27.264Z Running locally, skipping log reporting { resourceId: undefined, buildId: undefined }
[data-service-generator] error 2023-10-10T15:10:27.262Z Failed to execute plugin event CreateServer. Failed to execute plugin event CreateEntityServiceBase. The expression evaluated to a falsy value:
  assert_1.default.ok(lines instanceof linesModule.Lines)
 { resourceId: undefined,
  buildId: undefined,
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==',
  errorMessage:
   'Failed to execute plugin event CreateEntityServiceBase. The expression evaluated to a falsy value:\n\n  assert_1.default.ok(lines instanceof linesModule.Lines)\n',
  event: 'CreateServer',
  stack:
   'AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:\n\n  assert_1.default.ok(lines instanceof linesModule.Lines)\n\n    at new Patcher (/Users/user/workspace/amplication/amplication/node_modules/recast/lib/patcher.js:20:22)\n    at /Users/user/workspace/amplication/amplication/node_modules/recast/lib/patcher.js:138:23\n    at print (/Users/user/workspace/amplication/amplication/node_modules/recast/lib/printer.js:76:17)\n    at /Users/user/workspace/amplication/amplication/node_modules/recast/lib/printer.js:49:41\n    at Object.printComments (/Users/user/workspace/amplication/amplication/node_modules/recast/lib/comments.js:281:22)\n    at print (/Users/user/workspace/amplication/amplication/node_modules/recast/lib/printer.js:55:31)\n    at /Users/user/workspace/amplication/amplication/node_modules/recast/lib/printer.js:49:41\n    at FastPath.call (/Users/user/workspace/amplication/amplication/node_modules/recast/lib/fast-path.js:125:18)\n    at genericPrintNoParens (/Users/user/workspace/amplication/amplication/node_modules/recast/lib/printer.js:244:22)\n    at genericPrint (/Users/user/workspace/amplication/amplication/node_modules/recast/lib/printer.js:123:30)',
  cause: undefined }
```

### What you expected to happen

Code generation to complete successfully

### How to reproduce

Use the following [input.json](https://github.com/amplication/amplication/files/12858801/input.json) to reproduce.

1. Checkout the `master` branch of amplication/plugins repo  
3. Copy the file in `.amplication/generate-local-code/` folder
4. Update `"destPath": "plugins/plugins/auth-core"` with your local relative path to the plugin local repository
5. Run `npx nx generate-local-code data-service-generator`

**Comment by overbit** [comment]
Blocking #7182

**Comment by overbit** [comment]
@Shurtu-gal This is the issue related to the problem we're investigating

**Comment by Shurtu-gal** [comment]
After a lengthy debugging session the problem found was in this [code](https://github.com/benjamn/recast/blob/7f441d2c74d2cd61287fc6b498a9060f5597a27c/lib/patcher.ts#L27-#L28) which was resolving to falsy value due to the instance being different in plugin as the modules are all bundled.

I could find two possible solutions:- 

1. Change `memberExpression(_string_)` to `builders.memberExpression(_string_)` as the builder design ensures same instance.
2. As proposed by @overbit make **code-gen-utils** and **ast-types** into externals in `webpack.config.js`

Additionally, this situation has highlighted an interesting point - **the shared AST file**. It might be worth considering the idea of hoisting it into code-gen-utils for better organization and maintainability. However, before making this decision, some careful deliberation is needed. Everyone's insights on this matter would be greatly appreciated.
