### ISSUE TITLE
🐛 Bug Report: generated apps with Kafka fail to start

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#7654]
### What happened?

```sh
| [Nest] 1  - 12/18/2023, 1:25:32 PM     LOG [NestFactory] Starting Nest application...
server-1     | [Nest] 1  - 12/18/2023, 1:25:32 PM     LOG [InstanceLoader] AppModule dependencies initialized +26ms
server-1     | [Nest] 1  - 12/18/2023, 1:25:32 PM     LOG [InstanceLoader] AccessControlModule dependencies initialized +0ms
server-1     | [Nest] 1  - 12/18/2023, 1:25:32 PM     LOG [InstanceLoader] UserModuleBase dependencies initialized +0ms
server-1     | [Nest] 1  - 12/18/2023, 1:25:32 PM     LOG [InstanceLoader] PassportModule dependencies initialized +0ms
server-1     | [Nest] 1  - 12/18/2023, 1:25:32 PM     LOG [InstanceLoader] BatchModuleBase dependencies initialized +0ms
server-1     | [Nest] 1  - 12/18/2023, 1:25:32 PM     LOG [InstanceLoader] RouteModuleBase dependencies initialized +0ms
server-1     | [Nest] 1  - 12/18/2023, 1:25:32 PM     LOG [InstanceLoader] AssetModuleBase dependencies initialized +0ms
server-1     | [Nest] 1  - 12/18/2023, 1:25:32 PM     LOG [InstanceLoader] ProductionOrderModuleBase dependencies initialized +1ms
server-1     | [Nest] 1  - 12/18/2023, 1:25:32 PM     LOG [InstanceLoader] ItemModuleBase dependencies initialized +0ms
server-1     | [Nest] 1  - 12/18/2023, 1:25:32 PM     LOG [InstanceLoader] InventoryModuleBase dependencies initialized +0ms
server-1     | [Nest] 1  - 12/18/2023, 1:25:32 PM     LOG [InstanceLoader] TestModuleBase dependencies initialized +0ms
server-1     | [Nest] 1  - 12/18/2023, 1:25:32 PM     LOG [InstanceLoader] OperationModuleBase dependencies initialized +0ms
server-1     | [Nest] 1  - 12/18/2023, 1:25:32 PM     LOG [InstanceLoader] RouteRecipeModuleBase dependencies initialized +0ms
server-1     | [Nest] 1  - 12/18/2023, 1:25:32 PM     LOG [InstanceLoader] TestTypeModuleBase dependencies initialized +0ms
server-1     | [Nest] 1  - 12/18/2023, 1:25:32 PM     LOG [InstanceLoader] TestParameterModuleBase dependencies initialized +0ms
server-1     | [Nest] 1  - 12/18/2023, 1:25:32 PM     LOG [InstanceLoader] PrismaModule dependencies initialized +0ms
server-1     | [Nest] 1  - 12/18/2023, 1:25:32 PM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +1ms
server-1     | [Nest] 1  - 12/18/2023, 1:25:32 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +2ms
server-1     | [Nest] 1  - 12/18/2023, 1:25:32 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
server-1     | [Nest] 1  - 12/18/2023, 1:25:32 PM     LOG [InstanceLoader] HealthModule dependencies initialized +0ms
server-1     | [Nest] 1  - 12/18/2023, 1:25:32 PM   ERROR [ExceptionHandler] KAFKA_BROKERS environment variable must be definedundefined
server-1     | Error: KAFKA_BROKERS environment variable must be definedundefined
server-1     |     at generateKafkaClientOptions (/app/dist/kafka/generateKafkaClientOptions.js:11:15)
server-1     |     at InstanceWrapper.useFactory [as metatype] (/app/dist/kafka/kafka.module.js:27:130)
server-1     |     at Injector.instantiateClass (/app/node_modules/@nestjs/core/injector/injector.js:368:55)
server-1     |     at callback (/app/node_modules/@nestjs/core/injector/injector.js:65:45)
server-1     |     at async Injector.resolveConstructorParams (/app/node_modules/@nestjs/core/injector/injector.js:144:24)
server-1     |     at async Injector.loadInstance (/app/node_modules/@nestjs/core/injector/injector.js:70:13)
server-1     |     at async Injector.loadProvider (/app/node_modules/@nestjs/core/injector/injector.js:97:9)
server-1     |     at async /app/node_modules/@nestjs/core/injector/instance-loader.js:56:13
server-1     |     at async Promise.all (index 3)
server-1     |     at async InstanceLoader.createInstancesOfProviders (/app/node_modules/@nestjs/core/injector/instance-loader.js:55:9)

```

### What you expected to happen

Variables to be loaded as expected

### How to reproduce

1. Build a new service with a service broker and kafka plugin installed
2. follow the instruction for docker start up `npm run compose:up`

### Amplication version

v1.12.2

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by pmannion2** [comment]
Thank you team!
