### ISSUE TITLE
🐛 Bug Report: gRPC module creates duplicate rpc's in the <entity>.proto files that result in runtime errors

### ISSUE THREAD

**Issue by pmannion2** [amplication/amplication#7828]
### What happened?

Runtime built correctly, but threw this a few seconds into starting up. 

``` 
[Nest] 58012  - 01/17/2024, 12:42:21 PM   ERROR [Server] duplicate name 'updateBarrel' in Service BarrelService
Error: The invalid .proto definition (file at "undefined" not found)
    at ServerGrpc.loadProto (C:\Users\PatrickMannion\WebstormProjects\whk-wms\apps\whk-wms\node_modules\@nestjs\microservices\server\server-grpc.js:369:39)
    at ServerGrpc.bindEvents (C:\Users\PatrickMannion\WebstormProjects\whk-wms\apps\whk-wms\node_modules\@nestjs\microservices\server\server-grpc.js:42:34)
    at ServerGrpc.start (C:\Users\PatrickMannion\WebstormProjects\whk-wms\apps\whk-wms\node_modules\@nestjs\microservices\server\server-grpc.js:37:20)
    at ServerGrpc.listen (C:\Users\PatrickMannion\WebstormProjects\whk-wms\apps\whk-wms\node_modules\@nestjs\microservices\server\server-grpc.js:30:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

C:\Users\PatrickMannion\WebstormProjects\whk-wms\apps\whk-wms\node_modules\protobufjs\src\service.js:122
        throw Error("duplicate name '" + object.name + "' in " + this);
              ^
Error: duplicate name 'updateBarrel' in Service BarrelService
    at Service.add (C:\Users\PatrickMannion\WebstormProjects\whk-wms\apps\whk-wms\node_modules\protobufjs\src\service.js:122:15)
    at parseMethod (C:\Users\PatrickMannion\WebstormProjects\whk-wms\apps\whk-wms\node_modules\protobufjs\src\parse.js:764:16)
    at parseService_block (C:\Users\PatrickMannion\WebstormProjects\whk-wms\apps\whk-wms\node_modules\protobufjs\src\parse.js:710:17)
    at ifBlock (C:\Users\PatrickMannion\WebstormProjects\whk-wms\apps\whk-wms\node_modules\protobufjs\src\parse.js:290:17)
    at parseService (C:\Users\PatrickMannion\WebstormProjects\whk-wms\apps\whk-wms\node_modules\protobufjs\src\parse.js:704:9)
    at parseCommon (C:\Users\PatrickMannion\WebstormProjects\whk-wms\apps\whk-wms\node_modules\protobufjs\src\parse.js:269:17)
    at parse (C:\Users\PatrickMannion\WebstormProjects\whk-wms\apps\whk-wms\node_modules\protobufjs\src\parse.js:842:21)
    at process (C:\Users\PatrickMannion\WebstormProjects\whk-wms\apps\whk-wms\node_modules\protobufjs\src\root.js:127:30)
    at fetch (C:\Users\PatrickMannion\WebstormProjects\whk-wms\apps\whk-wms\node_modules\protobufjs\src\root.js:179:13)
    at Root.load (C:\Users\PatrickMannion\WebstormProjects\whk-wms\apps\whk-wms\node_modules\protobufjs\src\root.js:207:13)
λ WHK01-ET-L002 whk-wms → λ git main* →
````

### What you expected to happen

I suspect that gRPC needs unique names, and so a suffix is needed to make the udpate for the embedded reference unique compared to the update for main entity

### How to reproduce

This occurs for entities where there is an reference to another entity contained in an entity. The entity that is referenced by another entity will have duplicate names in the Proto file for both it's update, and the one for the update for the embedded reference in the other document. See the duplicate `updateBarrel` lines

```proto
service BarrelService {
 rpc createBarrel (BarrelCreateInput) returns (Barrel) {}
rpc barrels (findManyParams) returns (stream Barrel) {}
rpc barrel (BarrelWhereUniqueInput) returns (Barrel) {}
rpc updateBarrel (BarrelUpdateInput) returns (Barrel) {}
rpc deleteBarrel (BarrelWhereUniqueInput) returns (Barrel) {}
rpc findManyBarrel (BarrelWhereUniqueInput) returns (stream Sample) {}
rpc updateBarrel (SampleParams) returns (stream Sample) {}
rpc connectBarrel (SampleParams) returns (Sample) {}
rpc disconnectBarrel (SampleParams) returns (Sample) {} 
 }
```

### Amplication version

1.12.7

**Comment by PazYanoverr** [comment]
@mulygottlieb
