### ISSUE TITLE
🐛 Bug Report: `server` errors with Expected `join([])` to be called with an array of multiple elements, but got an empty array

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#8300]
### What happened?

```sh
TypeError: Expected `join([])` to be called with an array of multiple elements, but got an empty array
    at Object.ss [as join] (/app/main.js:1:179009)
    at UsageInsightsService.countBuilds (/app/main.js:7:38)
    at UsageInsightsService.getUsageInsights (/app/main.js:39:176)
    at UsageInsightsResolver.getUsageInsights (/app/main.js:1:1240940)
    at /app/node_modules/@amplication/opentelemetry-nestjs/dist/Trace/TraceWrapper.js:36:30
    at AsyncLocalStorage.run (node:async_hooks:330:14)
    at AsyncLocalStorageContextManager.with (/app/node_modules/@opentelemetry/context-async-hooks/build/src/AsyncLocalStorageContextManager.js:33:40)
    at ContextAPI.with (/app/node_modules/@opentelemetry/api/build/src/api/context.js:60:46)
    at Tracer.startActiveSpan (/app/node_modules/@opentelemetry/sdk-trace-node/node_modules/@opentelemetry/sdk-trace-base/build/src/Tracer.js:121:32)
    at UsageInsightsResolver.getUsageInsights (/app/node_modules/@amplication/opentelemetry-nestjs/dist/Trace/TraceWrapper.js:33:41)
``` 

### What you expected to happen

.

### How to reproduce

.

**Comment by overbit** [comment]
Test result ✅ 

![Image](https://github.com/amplication/amplication/assets/2861984/288f610f-1d0b-4475-abfd-57cefc5b0937)
