### ISSUE TITLE
Bug: Adding new Custom Action and navigating back and forth to it results in an empty screen and console errors

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#8785]
If you create a new Custom Action and then navigate to another action and back into the action you've just created, you will get a blank screen.
In the browser console you will find:
`vendor.5628304d40d266ee.js:1 TypeError: Cannot read properties of undefined (reading 'isArray')
    at P.i (2177.423c8ecb94947f08.js:1:8987)
    at Object.useMemo (vendor.5628304d40d266ee.js:1:777744)
    at t.useMemo (vendor.5628304d40d266ee.js:1:980353)
    at P (2177.423c8ecb94947f08.js:1:8728)
    at ka (vendor.5628304d40d266ee.js:1:771421)
    at ku (vendor.5628304d40d266ee.js:1:828276)
    at wl (vendor.5628304d40d266ee.js:1:817428)
    at gl (vendor.5628304d40d266ee.js:1:817356)
    at vl (vendor.5628304d40d266ee.js:1:817219)
    at al (vendor.5628304d40d266ee.js:1:814026)
    at ll (vendor.5628304d40d266ee.js:1:814415)
    at qi (vendor.5628304d40d266ee.js:1:755262)
    at vendor.5628304d40d266ee.js:1:811963
fs @ vendor.5628304d40d266ee.js:1
n.callback @ vendor.5628304d40d266ee.js:1
Bo @ vendor.5628304d40d266ee.js:1
_u @ vendor.5628304d40d266ee.js:1
wu @ vendor.5628304d40d266ee.js:1
bu @ vendor.5628304d40d266ee.js:1
(anonymous) @ vendor.5628304d40d266ee.js:1
El @ vendor.5628304d40d266ee.js:1
ll @ vendor.5628304d40d266ee.js:1
qi @ vendor.5628304d40d266ee.js:1
(anonymous) @ vendor.5628304d40d266ee.js:1Understand this error
vendor.5628304d40d266ee.js:1 Uncaught `

Refreshing the page solves the issue.

**Comment by morhag90** [comment]
Passed QA

https://github.com/user-attachments/assets/45539f43-8848-4762-b0aa-948a83d1bf3b
