### ISSUE TITLE
🐛 Bug Report: .NET build failed when using the Kafka Plugin

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#8851]
### What happened?

when using the Kafka plugin the build process fails and the following error is shown in the logs

```
'Error: socket hang up\n    at AxiosError.from (/workspace/packages/generator-dotnet-webapi/node_modules/axios/dist/node/axios.cjs:873:14)\n    at RedirectableRequest.handleRequestError (/workspace/packages/generator-dotnet-webapi/node_modules/axios/dist/node/axios.cjs:3152:25)\n    at RedirectableRequest.emit (node:events:517:28)\n    at eventHandlers.<computed> (/workspace/packages/generator-dotnet-webapi/node_modules/follow-redirects/index.js:38:24)\n    at ClientRequest.emit (node:events:517:28)\n    at Socket.socketOnEnd (node:_http_client:525:9)\n    at Socket.emit (node:events:529:35)\n    at endReadableNT (node:internal/streams/readable:1400:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)\n    at Axios.request (/workspace/packages/generator-dotnet-webapi/node_modules/axios/dist/node/axios.cjs:4262:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async BuildLogger.createLog (/workspace/packages/generator-dotnet-webapi/src/build-logger.js:14:13)\n    at async BuildLogger.logToBuildLog (/workspace/packages/generator-dotnet-webapi/src/build-logger.js:21:9)\n    at async BuildLogger.info (/workspace/packages/generator-dotnet-webapi/src/build-logger.js:29:9)\n    at async externalFormatting (/workspace/packages/generator-dotnet-webapi/src/generate-code.js:79:15)\n    at async generateCodeByResourceData (/workspace/packages/generator-dotnet-webapi/src/generate-code.js:91:13)\n    at async generateCode (/workspace/packages/generator-dotnet-webapi/src/generate-code.js:118:9)' }
```

### What you expected to happen

the process should complete succesfully 

### How to reproduce

Install the kafka plugin on a .NET service and rebuild the code

**Comment by mulygottlieb** [comment]
Passed QA ✅

`2024-09-05T13:33:01.030Z (Info) [server] Finalizing server creation...
2024-09-05T13:33:01.041Z (Info) [server] Normalizing modules path to use Unix path separator
2024-09-05T13:33:01.053Z (Info) [server] Creating application process finished successfully
2024-09-05T13:33:01.999Z (Info) [server] Formatting the generated code...
2024-09-05T13:33:27.432Z (Warning) [server] Warning ./Brokers/Mymessagebroker/MymessagebrokerMessageHandlersController.cs - Failed to compile so was not formatted.  (9,24): error CS1003: Syntax error, ',' expected  (9,26): error CS1002: ; expected  (9,41): error CS8124: Tuple must contain at least two elements.  (9,43): error CS1519: Invalid token '{' in class, record, struct, or interface member declaration  (12,32): error CS1519: Invalid token ';' in class, record, struct, or interface member declaration  (12,32): error CS1519: Invalid token ';' in class, record, struct, or interface member declaration  (14,1): error CS1022: Type or namespace definition, or end-of-file expectedFormatted 23 files in 1396ms.
2024-09-05T13:33:27.483Z (Info) [server] Code generation completed`
