### ISSUE TITLE
🐛 Bug Report: CI fails on amplication-server:package:container:production     

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#9049]
### What happened?

https://github.com/amplication/amplication/actions/runs/11203101532/job/31140131805

```
#11 28.54 npm ERR! code 7
#11 28.54 npm ERR! path /app/node_modules/bcrypt
#11 28.54 npm ERR! command failed
#11 28.54 npm ERR! command sh -c -- node-pre-gyp install --fallback-to-build
#11 28.54 npm ERR! node-pre-gyp info it worked if it ends with ok
#11 28.54 npm ERR! node-pre-gyp info using node-pre-gyp@1.0.11
#11 28.54 npm ERR! node-pre-gyp info using node@18.12.1 | linux | x64
#11 28.54 npm ERR! node-pre-gyp ERR! UNCAUGHT EXCEPTION 
#11 28.54 npm ERR! node-pre-gyp ERR! stack TypeError: Class extends value undefined is not a constructor or null
#11 28.54 npm ERR! node-pre-gyp ERR! stack     at Object.<anonymous> (/app/node_modules/tar/lib/read-entry.js:97:4)
#11 28.54 npm ERR! node-pre-gyp ERR! stack     at Module._compile (node:internal/modules/cjs/loader:1159:14)
#11 28.54 npm ERR! node-pre-gyp ERR! stack     at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
#11 28.54 npm ERR! node-pre-gyp ERR! stack     at Module.load (node:internal/modules/cjs/loader:1037:32)
#11 28.54 npm ERR! node-pre-gyp ERR! stack     at Module._load (node:internal/modules/cjs/loader:878:12)
#11 28.54 npm ERR! node-pre-gyp ERR! stack     at Module.require (node:internal/modules/cjs/loader:1061:19)
#11 28.54 npm ERR! node-pre-gyp ERR! stack     at require (node:internal/modules/cjs/helpers:103:18)
#11 28.54 npm ERR! node-pre-gyp ERR! stack     at Object.<anonymous> (/app/node_modules/tar/lib/pack.js:27:19)
#11 28.54 npm ERR! node-pre-gyp ERR! stack     at Module._compile (node:internal/modules/cjs/loader:1159:14)
#11 28.54 npm ERR! node-pre-gyp ERR! stack     at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
#11 28.54 npm ERR! node-pre-gyp ERR! System Linux 5.15.0-1073-azure
#11 28.54 npm ERR! node-pre-gyp ERR! command "/usr/local/bin/node" "/app/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
#11 28.54 npm ERR! node-pre-gyp ERR! cwd /app/node_modules/bcrypt
#11 28.54 npm ERR! node-pre-gyp ERR! node -v v18.12.1
#11 28.54 npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.11
#11 28.54 
#11 28.54 npm ERR! A complete log of this run can be found in:
#11 28.54 npm ERR!     /root/.npm/_logs/2024-10-06T15_48_31_156Z-debug-0.log
#11 ERROR: process "/bin/sh -c npm i --omit=dev" did not complete successfully: exit code: 7
```

### What you expected to happen

docker to build

### How to reproduce

see https://github.com/amplication/amplication/actions/runs/11203101532/job/31140131805

**Comment by MiirzaBaig** [comment]
Hello brother...@yuval-hazaz 
Afaik, is there any version mismatch b/w Node js or Npm ?

**Comment by mulygottlieb** [comment]
Passed QA
![Image](https://github.com/user-attachments/assets/5ff1318d-a2af-4e9b-b7e5-caa9e32f6206)
